### ISSUE TITLE
Convert pt locale to v2

### ISSUE THREAD

**Issue by adrm** [date-fns/date-fns#1012]
When I try to import the "pt" locale like this:

```typescript
import { enUS, es, it, pt } from "date-fns/locale";
```
All locales are imported correctly except for pt. I have seen that the index file in the locale folder is not including this locale even though it includes several others.

**Comment by adrm** [comment]
Well, I've seen that the pt locale is WIP, but there is no issue related. I will close this, but I would love to know what issue is tracking the progress with the pt locale.

Thanks.

**Comment by leshakoss** [comment]
@adrm `pt` locale is not converted to the v2 yet. We keep the list of locales like those here: https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json

There's no issue right now because no one volunteered to convert the locale yet.

PRs are very welcome! See the contribution guide: https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md
