### ISSUE TITLE
difference_in_days giving inconsistent results

### ISSUE THREAD

**Issue by pskd73** [date-fns/date-fns#1025]
Hi team,

I figured out one weird issue with difference_in_days function. Following are some trails and results
```
dayDiff("2018-12-17", new Date("2018-12-15"))
1 // expected: 2
dayDiff("2018-11-17", new Date("2018-11-15"))
1 // expected: 2
dayDiff("2018-1-17", new Date("2018-1-15"))
2 // correct
```

Why does the result change if we change the month from 1 to 11 and 12. I am using date-fns@1.29.0

**Comment by kossnocorp** [comment]
The problem is in date strings that you pass into the date constructor. date-fns v1 parses ISO strings and creates them in the local time zone while JS creates them in UTC, so you'll have an unexpected time shift. When you use numbers to create dates, then JS creates a date in the local timezone:

<img width="485" alt="image 2018-12-19 at 5 47 27 pm" src="https://user-images.githubusercontent.com/52201/50219861-844bc480-03b6-11e9-9ae5-e03ced04449f.png">

So you have to either parse the date using date-fns or use numbers in the constructor.
