### ISSUE TITLE
Make JSDoc arguments friendlier (dirtyDate -> date, dirtyStartDate -> startRangeDate)

### ISSUE THREAD

**Issue by LeshaKoss** [date-fns/date-fns#104]

**Comment by pke** [comment]
I still see a lot of `dirtyDate` and `dirtyAmount`. Whats up with that?

**Comment by leshakoss** [comment]
@pke they are just `date` and `amount` in docs (which this issue was about). We have a convention to use `dirty` as prefix for uncleaned/unconverted arguments in the source. This article: https://www.joelonsoftware.com/2005/05/11/making-wrong-code-look-wrong/ — may explain why. In short, it was made to make it more obvious when we forget to clean arguments to prevent bugs like #442
