### ISSUE TITLE
Afrikaans language support

### ISSUE THREAD

**Issue by JuergsPona** [date-fns/date-fns#1109]
Contributing to the project by adding support for the Afrikaans (af) language

**Comment by marnusw** [comment]
[Afrikaans](https://github.com/date-fns/date-fns/tree/master/src/locale/af) is already available in [v2](https://github.com/date-fns/date-fns/tree/master/src/locale/af) of `date-fns`. I'm pretty sure I also had it [merged for v1](https://github.com/date-fns/date-fns/pull/675) of the library, or at least early v2 before the locale format changed (since I don't see it on the 1.30.1 tag). If you're going to use date-fns v1 and not v2 it might be worth checking that out rather than redoing it all.

**Comment by JuergsPona** [comment]
@marnusw I was actually looking at your code now (didn't see it when I opened the issue)

I see v2 is still in alpha, and I'm currently using v1 (that's where I didn't see it)

Sorry about the confusion, I should have looked through the code before I went full speed ahead 😁 

How would I add it to v1?

**Comment by marnusw** [comment]
It might be good to hear from @kossnocorp if he wouldn't mind clarifying, but one way might be to create a new feature branch off of the last v1 branch (or tag, not sure which branch it would be) and cherry-picking the commits I made that are compatible with v1. Then that could be merged via a new PR.

If the maintainers aren't doing any new releases on v1 at the moment it might be easier to just copy that `af` locale directly into your project until v2 goes into beta and you can upgrade.

**Comment by JuergsPona** [comment]
I think I'll just fork v1 for now and add the translations. Not a train smash, but thanks so much for your assistance. I'll close this off
