### ISSUE TITLE
Add more patterns to lightFormat

### ISSUE THREAD

**Issue by ovvn** [date-fns/date-fns#1110]
Is it possible to add more frequently used patterns to the lightFormat? For example, we use 'MMM' and 'MMMM' often.

**Comment by ovvn** [comment]
As I understood such formatters were removed from lightFormat because they use locales. But maybe we could use some "default locale", e.g. en-us in lightFormat for the locale formatters instead of removing them completely.

**Comment by kossnocorp** [comment]
As you assumed, these tokens were removed because adding default locale to `lightFormat` would make it not so light. In the future, we'll try to make both `format` and `parse` more lightweight or add something like `lightFormat` directly to locales but for the time being please use `format` if you need month names.
