### ISSUE TITLE
Problem with init hour - startOfDay

### ISSUE THREAD

**Issue by MarceloBaeza** [date-fns/date-fns#1126]
Hi everyone, I have a problem with starOfDay(), when I set Date **2018-12-07T16:30:00.000Z** this function returns **Date 2018-12-07T19:00:00.000Z** (I only set the hour). When I call **startOfDay(new Date())**, returns: **2018-12-07T03:00:00.000Z.** How I set default init hour?
Thx.

**Comment by Maryna-Yelakova** [comment]
I have similar problem. When I set "2019-04-06T21:00:00Z" startOfDay() returns Sun Apr 07 2019 00:00:00 GMT+0300

**Comment by kossnocorp** [comment]
That happens because you store dates in UTC, but when you create a date from it, it transforms to the **local** time zone:

```js
new Date("2019-04-06T21:00:00Z").toString()
//=> "Sun Apr 07 2019 01:00:00 GMT+0400 (Samara Standard Time)"
```

When there was 21:00 in UTC, it was actually 01:00 (next day) in my local timezone. And that's the correct behavior.

I can suggest you solutions, but they depend on what you are trying to achieve.

Please reopen the issue with more details about your use case so I can help you.
