### ISSUE TITLE
Can't resolve 'date-fns/distanceInWords'

### ISSUE THREAD

**Issue by GitHubGreg** [date-fns/date-fns#1146]
I've updated to 2.0.0-alpha.27 to get access to fromUnixTime.

But I received an error in other components where I used distance_in_words:
`Can't resolve 'date-fns/distance_in_words'`

I therefore changed it to distanceInWords but still get an error:
`Can't resolve 'date-fns/distanceInWords'`

**Comment by iampeterbanjo** [comment]
I had a similar issue with importing locale. Please see #666 

From the thread your issue might be due to changes in the alpha release:
> At the moment just a few locales are compatible with v2. See the list: https://github.com/date-fns/date-fns/blob/master/src/esm/locale/index.js. I also fixed a typo in the I18n doc: #741

Looking at the [exported modules in the source code](https://github.com/date-fns/date-fns/blob/master/src/index.js) I would say that `distance_in_words` is not exported in your version. Maybe you're looking for [version 1.30.x](https://date-fns.org/v1.30.1/docs/distanceInWords)

**Comment by kossnocorp** [comment]
The function was renamed to `formatDistance`, see: https://date-fns.org/v2.0.0-alpha.27/docs/formatDistance
