### ISSUE TITLE
Expected behaviour for parse(null) - epoch or invalid date?

### ISSUE THREAD

**Issue by dteirney** [date-fns/date-fns#1148]
We recently ran into an unexpected output from parse that seems inconsistent. When `null` is passed as the argument the epoch is returned (similar to if 0 had been supplied).

We'd have expected an invalid date to be returned for this case, to match what happens when `undefined` is provided. The standard behaviour for Date appears to be return `NaN` when `null` is supplied, as happens when `undefined` is provided.

Below are some console snippets from the web-site - very handy thanks! https://date-fns.org/v1.30.1/docs/parse

```
dateFns.parse(null)
Thu Jan 01 1970 12:00:00 GMT+1200 (New Zealand Standard Time)
dateFns.parse()
Invalid Date
dateFns.parse(undefined)
Invalid Date
dateFns.parse(0)
Thu Jan 01 1970 12:00:00 GMT+1200 (New Zealand Standard Time)
Date.parse(null)
NaN
Date.parse(undefined)
NaN
```

**Comment by minitesh** [comment]
@dteirney 

I think as per the documentation, if the argument passed is not either string, number of Date instance, the function passes the given argument to Date constructor.
So it will call `new Date(<ARGUMENT>)` instead of `Date.parse(<ARGUMENT>)`

`
dateFns.parse(null)
Date 1970-01-01T00:00:00.000Z
new Date(null)
Date 1970-01-01T00:00:00.000Z

dateFns.parse(undefined)
Invalid Date
new Date(undefined)
Invalid Date

dateFns.parse(0)
Date 1970-01-01T00:00:00.000Z
new Date(0)
Date 1970-01-01T00:00:00.000Z

dateFns.parse()
Invalid Date
new Date()
Date 2019-04-25T05:28:05.013Z
`

So as per above scenarios, it is working rightly except for the case when we don't pass anything to `dateFns.parse`.

**Comment by dteirney** [comment]
Thanks for the reply. I guess we chalk this up to yet another inconsistency in how Date parsing is handled in ECMA Script.

```
new Date(null)
Thu Jan 01 1970 12:00:00 GMT+1200 (New Zealand Standard Time)
Date.parse(null)
NaN
new Date(undefined)
Invalid Date
Date.parse(undefined)
NaN
new Date()
Tue May 21 2019 12:53:08 GMT+1200 (New Zealand Standard Time)
Date.parse()
NaN
```

Is there a reason the Date constructor is used rather than `Date.parse()` when the function in `date-fns` is called `parse`? At least for our usage scenarios where we are parsing content from API responses, the behavior  of `Date.parse()` fits better with what we had expected.

**Comment by kossnocorp** [comment]
We have changed the behavior in v2, now all functions implicitly convert arguments by following rules:

  |           | date          | number | string      | boolean |
  |-----------|---------------|--------|-------------|---------|
  | 0         | new Date(0)   | 0      | '0'         | false   |
  | '0'       | Invalid Date  | 0      | '0'         | false   |
  | 1         | new Date(1)   | 1      | '1'         | true    |
  | '1'       | Invalid Date  | 1      | '1'         | true    |
  | true      | Invalid Date  | NaN    | 'true'      | true    |
  | false     | Invalid Date  | NaN    | 'false'     | false   |
  | null      | Invalid Date  | NaN    | 'null'      | false   |
  | undefined | Invalid Date  | NaN    | 'undefined' | false   |
  | NaN       | Invalid Date  | NaN    | 'NaN'       | false   |
