### ISSUE TITLE
Format API returns previous day

### ISSUE THREAD

**Issue by jameytsg** [date-fns/date-fns#1171]
Thank you for all that you do! Big fan of your work.

**Issue:**
Feeding "today" to `format` returns "yesterday"

For context, these screenshots were taken 5/16/2019.

In the console log photo, the original date string returns the 16th. When it passes through `format` it transforms to the 15th. (and so forth relative to the passed date)

**Example:**
https://codesandbox.io/s/datefns-issue-1171-wfzk4

![code](https://user-images.githubusercontent.com/48097938/57862971-3ef5bc80-77c7-11e9-9a36-65684a23a474.PNG)
![console](https://user-images.githubusercontent.com/48097938/57862974-4026e980-77c7-11e9-8fe9-019851176ea4.PNG)

**Comment by y6nH** [comment]
Makes sense if you're in a timezone west of UTC. Because a date without a time resolves to 00:00:00, if you're in, say, Rio, in UTC-3, it's still 9PM the previous day when it's midnight on the Meridian.

**Comment by jameytsg** [comment]
Never thought of it like that. Interesting.

I'm trying to think of the best way to do something like this

```
const numberOfDaysDisplayed = 14;
  const startDate = Date.now();
  const endDate = Date.now() + 1000 * 60 * 60 * 24 * numberOfDaysDisplayed;
  const buildDatesArr = eachDayOfInterval({
    start: startDate,
    end: endDate,
  });
```

Wondering how I would avoid that issue?

**Comment by kossnocorp** [comment]
As @y6nH noted, because you store dates in UTC strings depending on your timezone you'll be getting different results. If these dates are coming from the API you can process them like that:

```js
const [year, month, day] = "2019-06-03T00:00:00.000Z".slice(0, 10).split('-').map(n => parseInt(n))
const date = new Date(year, month - 1, day)
//=> Mon Jun 03 2019 00:00:00 GMT+0400 (Samara Standard Time)
```

I know that's not ideal, but the problem will be solved with the introduction of UTC functionality.

If you create dates in the browser `eachDayOfInterval` should help you. If it's not a case, please describe what problems you have with it and reopen the issue.
