### ISSUE TITLE
Is this library pure?

### ISSUE THREAD

**Issue by light0x00** [date-fns/date-fns#1193]
It's a great project. I love it.
But I see sideEffect is not set in package.json.
so Is this library pure?

**Comment by TrySound** [comment]
sideEffects field does not mean the library is pure. It's mostly a hack for webpack analyzer. Rollup uses it too but it's useful for more complicated cases like transpiled classes. This library is written with only functions.

**Comment by kossnocorp** [comment]
> It's a great project. I love it.

Thank you a lot!

> But I see sideEffect is not set in package.json.

It's set in v2 to `false` in the root directory and each module.

> so Is this library pure?

It depends on what you mean by pure. The library code doesn't produce side effects so can be tree-shaken (that's why we have `sideEffects`). If you mean FP-pure, then yes it doesn't use `Date.now` at the moment but I'm going to change that, see #1184 but anyways `date-fns/fp` will stay pure.
