### ISSUE TITLE
wrong format from dateTime in formatLong 

### ISSUE THREAD

**Issue by HosseinAlipour** [date-fns/date-fns#1251]
I'm new to date-fns and using v2.beta.2, I was expecting [this sandbox](https://codesandbox.io/s/wfvby) to print full date and time but I'm getting `{{8AM15599428107}} at {{15599428106567}} `. I look in source code and saw [this ](https://github.com/date-fns/date-fns/blob/master/src/locale/en-GB/_lib/formatLong/index.js#L17) and [this ](https://github.com/date-fns/date-fns/blob/master/src/locale/_lib/buildFormatLongFn/index.js) function to be responsible and incompatible, the function needs to replace date and time with formats. Do you need a PR for this? and I couldn't find any documentation for this, are there any alternatives?

**Comment by kossnocorp** [comment]
Hey, there are special tokens for that: https://codesandbox.io/embed/date-plpst

See "Long localized date", "Long localized time" and "Combination of date and time" in the tokens table for more details: https://date-fns.org/v2.0.0-beta.2/docs/format

**Comment by udonmai** [comment]
I think the issue here is that the locale specific functions for datetime format return
```
{
  full: '{{date}} {{time}}',
  long: '{{date}} {{time}}',
  medium: '{{date}} {{time}}',
  short: '{{date}} {{time}}'
};
```

and `{{date}} {{time}}` is not a valid format for date-fns/format to parse.

while for different locales, the combination of {{date}} and {{time}} is different that's why we need this format from the locales.

The workaround here now could only be do parsing by outselves to replace the date and time by ourselves.

@kossnocorp
