### ISSUE TITLE
Incorrect results using addHours & subHours when crossing DST

### ISSUE THREAD

**Issue by mlieu** [date-fns/date-fns#1302]
Getting incorrect results with `addHours` and `subHours`  when crossing DST.

DST for the Eastern time ended on November 3 at 2:00 am, and started again on March 3 at 3:00 am.

Example:
``` typescript
const date1 = new Date('2018-11-03T06:00');
console.log(addHours(date1, 24));
// getting 2018-11-03T05:00, should be 2018-11-04T06:00

const date2 = new Date('2019-03-10T06:00');
console.log(subHours(date2, 24));
// getting 2019-03-09T05:00, should be 2019-03-09T06:00
```

**Comment by kossnocorp** [comment]
Thank you for reporting it! This looks like a bug!

**Comment by kossnocorp** [comment]
What's your local timezone?

**Comment by mlieu** [comment]
I'm using Eastern Time

**Comment by Imballinst** [comment]
Hey, lemme know if this is correct:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/7077157/66174762-0ed98800-e69a-11e9-8ac0-d5e5e384affb.png">

for `date1`, you were using last year's -- which happens to be correct (?) because it ends November 4, 2am instead of November 3. Tested it in the browser as well:

<img width="463" alt="Screen Shot 2019-10-03 at 9 22 19 PM" src="https://user-images.githubusercontent.com/7077157/66174812-49432500-e69a-11e9-8b2e-40119ba3d173.png">

Similarly, for 2019 DST:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/7077157/66174826-5233f680-e69a-11e9-8761-705104d4182f.png">

<img width="458" alt="image" src="https://user-images.githubusercontent.com/7077157/66174835-5b24c800-e69a-11e9-9731-fa946bdcadff.png">

because the timezone lags one hour, then it makes sense for the time itself to "lag" one hour as well.

**Comment by mlieu** [comment]
If it lags one hour, then is there no way to get the previous day at the same time without having to keep track of the days (and ignoring the local time change)? It sounds like I would always need to check when to add/sub 24 hours vs. 25 or 26 hours to make up for the time change?

**Comment by justingrant** [comment]
@mlieu - As far as I can tell, this is not a bug. date-fns is correctly adding/subtracting 24 hours regardless of whether there's a DST transition between the two dates. To verify, convert the times to UTC and you'll see that they're indeed 24 hours apart: 
```
const date1 = new Date('2018-11-03T06:00');
console.log(date1.toISOString()); // 2018-11-03T13:00:00.000Z 
const date2 = addHours(date1, 24)
console.log(date2.toISOString()); // 2018-11-04T13:00:00.000Z 
```

To get the previous day at the same time, use `addDays` or `subDays`. These APIs respect daylight savings time and try to keep local time constant.

I believe that this issue should be closed.

**Comment by kossnocorp** [comment]
@justingrant you're right, thank you for the input!
