### ISSUE TITLE
version 2 is much bigger than v1

### ISSUE THREAD

**Issue by tuananh** [date-fns/date-fns#1303]
https://bundlephobia.com/result?p=date-fns@2.0.0

**Comment by leshakoss** [comment]
This is true, v2 contains ~40 new functions, including bigger [`format`](https://date-fns.org/v2.0.0/docs/format), it's light alternative [`lightFormat`](https://date-fns.org/v2.0.0/docs/lightFormat), new huge [`parse`](https://date-fns.org/v2.0.0/docs/parse) and many more.

But it's not intended for the whole library to included in the bundle at once. Date-fns's real lightweight-ness compared to the other JS date utility libraries is more obvious when you're importing only individual functions or are using [tree-shaking](https://date-fns.org/v2.0.0/docs/ECMAScript-Modules) if your bundler supports it.

In fact, because we extracted [ISO-8601 parser](https://date-fns.org/v2.0.0/docs/parseISO) from being included in every function, [the minimal build size of date-fns v2 is smaller than v1's](https://blog.date-fns.org/post/we-cut-date-fns-v2-minimal-build-size-down-to-300-bytes-and-now-its-the-smallest-date-library-18f2nvh2z0yal)!

Thanks for trying v2!
