### ISSUE TITLE
I can't recommend this library.

### ISSUE THREAD

**Issue by ksevksev** [date-fns/date-fns#1305]
I'd like to recommend this library, but I can't. They are releasing a new version while they have let serious defects sit. These are defects that are getting attention from developers and causing issues. Sorry, I just can't recommend it.

**Comment by leshakoss** [comment]
@ksevksev hello, thank you for trying v2! Please [open an issue](https://github.com/date-fns/date-fns/issues/new) and describe the problem you're having, we'll be glad to help!

**Comment by mikeerickson** [comment]
@ksevksev don’t you think it would be more productive to mention (or report) these so called issues that exist instead of just complaining.

For those who happen to read this post, I have been using the 2.x pre release for over six months in many production apps and have not had a single issue. 

So, I CAN highly recommend and prefer it to the bloated MomentJS
