### ISSUE TITLE
Wrong translation for French.

### ISSUE THREAD

**Issue by Dallas62** [date-fns/date-fns#1391]
Hi!

When we use the format `iiii do MMMM yyyy`, we should have this translation:

"Jeudi 1er août 2019" and "Jeudi 29 août 2019"
but we have:
"Jeudi 1er août 2019" and "Jeudi 29[**ème**](#) août 2019"
                                                           
There is an extra "ième" when the day is greater than 1, this should not happen.

[src/locale/fr/_lib/formatters/index.js](https://github.com/date-fns/date-fns/blob/master/src/locale/fr/_lib/formatters/index.js) is not included / loaded and use the wrong format (`Do` instead of `do`). I didn't know how to do it. `formatters` is not used when I place it in the `locale`... and the engine seems to ignore it...

It does not break the functionalities but it's a bad "experience" for users... I can replace it if French, but... 😄 

Regards

**EDIT**:
New link in v3: https://github.com/date-fns/date-fns/blob/main/src/_lib/format/formatters/index.ts#L317

**Comment by dkozickis** [comment]
@Dallas62 thank you for reporting, PR is welcome!

Ordinal numbers can be edited here

https://github.com/date-fns/date-fns/blob/master/src/locale/fr/_lib/localize/index.js#L61

**Comment by Dallas62** [comment]
@dkozickis Hi !

The issue is not about a problem with ordinal number in general, but ONLY on the case you choose "do MMMM".

It sound's good to say:
"Le 3ème jour de la semaine"

**Comment by dkozickis** [comment]
Right, this looks like a regression from v1.

https://github.com/date-fns/date-fns/blob/master/src/locale/fr/_lib/formatters/index.js you mention is not used anymore as far as I can see, due to formatters restructure, it seems.

Good way forward here seems to be passing next token (maybe as part of `formatterOptions') to selected `formatter` function in `format` https://github.com/date-fns/date-fns/blob/ff7b6e1b15fa19e3b5613b1fb68c93abb7d99a1d/src/format/index.js#L451

then determine if next token is a month token and pass that information further to `ordinalNumber` options

https://github.com/date-fns/date-fns/blob/ff7b6e1b15fa19e3b5613b1fb68c93abb7d99a1d/src/_lib/format/formatters/index.js#L292

then we'll have that information in `ordinalNumber` locale function and we'll be able to determine suffix correctly

**Comment by robotvert** [comment]
Also, may I add, the `ème` and such suffixes are incorrect: http://www.academie-francaise.fr/abreviations-des-adjectifs-numeraux

**Comment by drasill** [comment]
I also confirm this, which make the `do` pattern useless in french.

**Comment by Dallas62** [comment]
Hi @dkozickis 
I just check how to create a test case then make a PR, but sorry the project is too hard to understand where to start.

**Comment by dkozickis** [comment]
@kossnocorp what's your opinion on how to procede here?

**Comment by antoinerousseau** [comment]
any help needed on this? I can try to open a PR.

**Comment by reDim89** [comment]
The issue still happens in the latest version of the package.
There's wrong `ème` suffix added for French locales.

Incorrect: `19ème janvier 2023` 
Correct: `19 janvier 2023`

**Comment by reDim89** [comment]
@antoinerousseau sorry, may be you can help one more time with this issue?

**Comment by Dallas62** [comment]
@kossnocorp @dkozickis Is there any update about this case ?
It's really weird to keep a "workaround" that replace the string...

**Comment by kossnocorp** [comment]
@antoinerousseau or anyone else is welcome to send a PR. I'll make sure it's shipped soon.

**Comment by antoinerousseau** [comment]
Voilà :)

**Comment by fturmel** [comment]
Would love everyone's feedback on #3662!
