### ISSUE TITLE
How to format utc like moment.js?

### ISSUE THREAD

**Issue by Hx2heng** [date-fns/date-fns#1401]
Is there any way to do like this by date-fns?
```
let now = new Date().getTime();
// after some time...
moment.utc(new Date().getTime() - now).format(' ( HH:mm:ss )');
```

date-fns has `formatDistance()` ,but I don't need the result in words.

**Comment by atilkan** [comment]
It is not supported, yet! That reason made me switch to moment.

**Comment by dkozickis** [comment]
@Hx2heng what is the expected output here?

**Comment by Hx2heng** [comment]
> @Hx2heng what is the expected output here?

the duration format to ' ( HH:mm:ss )'

**Comment by dkozickis** [comment]
One of the ways of doing it, yep.

**Comment by ron-liu** [comment]
> It is not supported, yet! That reason made me switch to moment.

seems I have to do the same.

**Comment by kossnocorp** [comment]
@ron-liu what was your motivation in writing this comment? Did you want to ruin my day? I hope not, but I can't find another explanation. 

There're solutions to the problem, and one very fine is listed in the comments. If you spent some time reading docs, you would find [date-fns-tz](https://www.npmjs.com/package/date-fns-tz). So clearly, it's not the lack of options that made you post it. Did you add something to the discussion? I don't see how.

[I don't care, but such behavior is hurtful to others, so please, for community sake, think how your comment could resonate on another end before posting it](https://github.com/kossnocorp/etiquette#dont-cause-drama).

**Comment by atilkan** [comment]
@kossnocorp start being nice if are asking for it. He did not mean no harm obviously. 
And my comment is old. He should just checked docs again. That is what you could do. Instead of giving lecrure, direct people to the docs.

**Comment by kossnocorp** [comment]
@atilkan I do it all the time as much to the best of my ability and availability. And I'm being nice spending many years working on the library and guess what, I can lecture people being rude to me as much as I want.

**Comment by atilkan** [comment]
@kossnocorp Dude, he is not being rude. I suppose you are not on the mood today. Thank you for the great work though.

**Comment by atilkan** [comment]
For anyone comin here; **date-fns** doesn't support utc formats at its core but it has a solution. 
Here check the docs. https://date-fns.org/v2.8.1/docs/Time-Zones#date-fns-tz

@kossnocorp  Maybe you can close the issue.

**Comment by kossnocorp** [comment]
@atilkan look, I understand that you don't see the problem and on top being annoyed by a lecture from a rando from the internet. I perfectly get it.

But try to see the problem from my side: I wake up and see that people leave date-fns. Am I not working hard enough? Is it so bad? It stings and puts unnecessary pressure, which is not helpful and only makes me (and other maintainers) procrastinate instead of working on a solution. Such comments are hurtful.

So for me, it's rude. Go to Moment.js repo, announce that you're leaving to date-fns, and they will say you the same. I guarantee that.

There's a problem in our culture. Users often look at open-source maintainers as on service staff that sell them a product. I understand why it so, and we ourselves a big part of the problem.

And over the years, it's become worse, so I decided to try to change it. [I come up with a list of issues that I see and show people the perspective of a maintainer when I have a chance](https://github.com/kossnocorp/etiquette). That's not always pleasant because it's hard to be friendly while doing it and not everyone knows how to own it, but I have a lot of patience. I also do it in my domain, where I'm actually entitled to it.

There's an important disclaimer. I got used to it. I don't enjoy it, but it doesn't hurt me that much, but I remember how I struggled with it for many years and know for sure that many people struggle with it too.

Again, I'm trying this hard not because I extremely offended or "got triggered" (maybe a little ;-) but because I believe that I can change something.

**Comment by atilkan** [comment]
@kossnocorp I don't think people leaving date-fns. I advertise it as much as i can. Even though couple monts ago i had to leave, it was temporary, i always checked the news and docs. 
So be patiant. This is a good library, people are coming. Don't get frustrated by haters but also listen for critics.

**Comment by cwilby** [comment]
I'm migrating a project from moment at the.. _moment_

I have to step away for a mome..

**Comment by cwilby** [comment]
I'm currently migrating from moment to date-fns and it's going great.  Thanks for all the hard work @kossnocorp.

**Comment by andrewsm80** [comment]
@cwilby That code is not correct, although it will appear to work most of the time.
For example, in my timezone (America/Halifax) there is no such thing as `02:00 AM March 8th, 2020` because of changer to DST, from `1:59 AM` to `3:00 AM`.
`format()` will never format to `2:00 AM`  in my timezone because it thinks you are asking for a local time, even if you try to fool it by adding an offset.

```
let format = require("date-fns/format");
let addMinutes = require("date-fns/addMinutes");
function formatDate(date) {
  return format(addMinutes(date, date.getTimezoneOffset()), 'yyyy-MM-dd HH:mm:ss');
}

// My timezone is UTC-4 at "2020-03-08T01:59" local.
// One minute passes and my timezone becomes UTC-3 at "2020-03-08T03:00" local.
// So in my timezone, "formatDate()" will never display "2:00 AM" on March 8th, 2020.
// So it gives the wrong answer once a year.
let d1 = new Date("2020-03-07T21:59");
console.log(formatDate(d1));

let d2 = new Date("2020-03-07T22:00");
console.log(formatDate(d2));


```

**Comment by cwilby** [comment]
@andrewsm80 Good point - edited answer.

I since refactored this function since Laravel started serializing dates in ISO-8601 format.  It now uses the included UTC offset instead.

**Comment by chojnicki** [comment]
So why issue is closed exactly? Since it is not fixed in any way

**Comment by cwilby** [comment]
> So why issue is closed exactly? Since it is not fixed/resolved in any way except that not-so-pretty workaround that "doesn't work for all time zones.

A previous version of the solution I posted calculated the offset incorrectly, resulting in the issue @andrewsm80 reported.  

The latest version gets the offset from the browser, producing a correct result.

**Comment by jacob-lcs** [comment]
> 

How should `endofDay` be used in this case?

**Comment by zenstok** [comment]
> @cwilby That code is not correct, although it will appear to work most of the time. For example, in my timezone (America/Halifax) there is no such thing as `02:00 AM March 8th, 2020` because of change to DST, from `1:59 AM` to `3:00 AM`.
> 
> `format()` will never format to `2:00 AM` on the second Sunday of March in my timezone because it thinks you are asking for a local time, even if you try to fool it by adding an offset.

It looks like the actual problem lies within addMinutes function.
If you set the date like this it will format it correctly anytime:

```
import { format, addMinutes } from 'date-fns';
                
function formatDate(date) {
  const offsetDate = new Date(
    new Date(
      new Date(date).setMinutes(
        new Date(date).getMinutes() + new Date(date).getTimezoneOffset(),
      ),
    ),
  );
  
  return format(offsetDate, 'yyyy-MM-dd HH:mm:ss');
}

```

**Comment by cwilby** [comment]
@zenstok ¯\_(ツ)_/¯
