### ISSUE TITLE
Adding one month results in 29 days

### ISSUE THREAD

**Issue by otaviobps** [date-fns/date-fns#1510]
I'm using the `addMonths` function to add 1 month to a given date. The function is inside a `forEach` but that doesn't add nothing to the bug.

Receiving the date `2019-03-01T01:00:00.000Z` and adding 1 month to it `dateFns.addMonths(actualDate, 1)` (actualDate is the referred date object) results in `2019-04-29T01:00:00.000Z` when it should result `2019-05-01T01:00:00.000Z`. I tried starting in 2019-01-01 and add 1 month to each new date. Here are the resulting dates:

```
2019-02-01T00:00:00.000Z
2019-03-01T01:00:00.000Z
2019-03-29T01:00:00.000Z
2019-04-29T01:00:00.000Z
2019-05-29T01:00:00.000Z
2019-06-29T01:00:00.000Z
2019-07-29T01:00:00.000Z
2019-08-29T01:00:00.000Z
2019-09-29T01:00:00.000Z
2019-10-29T01:00:00.000Z
```

Beginning in 2018-01-01, the resulting dates are:

```
2018-02-01T00:00:00.000Z
2018-03-01T01:00:00.000Z
2018-03-29T01:00:00.000Z
2018-04-29T01:00:00.000Z
2018-05-29T01:00:00.000Z
2018-06-29T01:00:00.000Z
2018-07-29T01:00:00.000Z
2018-08-29T01:00:00.000Z
2018-09-29T01:00:00.000Z
2018-10-29T01:00:00.000Z
2018-11-29T00:00:00.000Z
2018-12-29T00:00:00.000Z
2019-01-29T00:00:00.000Z
2019-03-01T01:00:00.000Z
2019-03-29T01:00:00.000Z
2019-04-29T01:00:00.000Z
2019-05-29T01:00:00.000Z
2019-06-29T01:00:00.000Z
2019-07-29T01:00:00.000Z
2019-08-29T01:00:00.000Z
2019-09-29T01:00:00.000Z
2019-10-29T01:00:00.000Z
```

My `nodejs` version is 12.12.0 and `date-fns` version is `2.6.0`

**Comment by leshakoss** [comment]
@otaviobps hi, could you please tell us what timezone are you in?

**Comment by otaviobps** [comment]
Hi @leshakoss, I'm in GMT-3

**Comment by tanoabeleyra** [comment]
We recently realized about this bug in one project. We're also in the GMT-3 timezone.

**Comment by dkozickis** [comment]
@otaviobps / @tanoabeleyra can we get your exact timezones please?

```javascript
Intl.DateTimeFormat().resolvedOptions().timeZone
//=> 'Asia/Makassar'
```

**Comment by otaviobps** [comment]
My timezone is America/Sao Paulo.

However since my project was live, I had to move to Moment, so I can't replicate this bug anymore

**Comment by tanoabeleyra** [comment]
Mine is `"America/Buenos_Aires"`. And date-fns version 2.7.0.

**Comment by justinvos** [comment]
Same issue here, and my timezone is Pacific/Auckland. With date-fns version 2.7.0 and node 10.17.0.

**Comment by tanoabeleyra** [comment]
Any update on this?

**Comment by lolgesten** [comment]
Repro in GMT+11

```
> require('date-fns').addMonths(new Date("2017-09-01T00:00:00.000Z"), 1)
2017-09-30T23:00:00.000Z
```

**Comment by lolgesten** [comment]
I think I understand the problem.

date-fns uses this technique in a lot of tests, and also some places in the actual functions.

```js
    var date = new Date(0)
    date.setFullYear(2020, i, 1);
```

The problem is that `setFullYear` is both sensitive to daylight savings. Here's a simple test I ran while my computer was on the date 2020-01-16  in three timezones. Madrid, India and Australia.

```js
  for(var i = 0; i <= 11; i++) {
    var date = new Date(0)
    date.setFullYear(2020, i, 1);
    console.log(date);
  }
```

### Madrid

```
2020-01-01T00:00:00.000Z
2020-02-01T00:00:00.000Z
2020-03-01T00:00:00.000Z
2020-03-31T23:00:00.000Z
2020-04-30T23:00:00.000Z
2020-05-31T23:00:00.000Z
2020-06-30T23:00:00.000Z
2020-07-31T23:00:00.000Z
2020-08-31T23:00:00.000Z
2020-09-30T23:00:00.000Z
2020-11-01T00:00:00.000Z
2020-12-01T00:00:00.000Z
```

### India

India doesn't do DST.

```
2020-01-01T00:00:00.000Z
2020-02-01T00:00:00.000Z
2020-03-01T00:00:00.000Z
2020-04-01T00:00:00.000Z
2020-05-01T00:00:00.000Z
2020-06-01T00:00:00.000Z
2020-07-01T00:00:00.000Z
2020-08-01T00:00:00.000Z
2020-09-01T00:00:00.000Z
2020-10-01T00:00:00.000Z
2020-11-01T00:00:00.000Z
2020-12-01T00:00:00.000Z
```

### Melbourne

```
2019-12-31T23:00:00.000Z
2020-01-31T23:00:00.000Z
2020-02-29T23:00:00.000Z
2020-03-31T23:00:00.000Z
2020-05-01T00:00:00.000Z
2020-06-01T00:00:00.000Z
2020-07-01T00:00:00.000Z
2020-08-01T00:00:00.000Z
2020-09-01T00:00:00.000Z
2020-10-01T00:00:00.000Z
2020-10-31T23:00:00.000Z
2020-11-30T23:00:00.000Z
```

With that in mind, here's the [code for this function](https://github.com/date-fns/date-fns/blob/62eecac8247f33dd77e059803191811a3519cc6d/src/addMonths/index.js#L33-L35)

Date does not have a notion of timezone, we expect `addMonths` for `new Date('2020-01-01T00:00:00.000Z')` to be offset from that exact time, but `setFullYear` operates in the current time zone (and it gets further muddled with `setHours(0,0,0,0)`, same problem).

One solution would be to use `setUTCFullYear`, but maybe that's breaking compatibility?

**Comment by justingrant** [comment]
I believe that this behavior is NOT a bug, but is expected behavior because date-fns only uses the user time zone, not UTC, to evaluate date boundaries and to preform date calculations. For example, I'm in the America/Los Angeles timezone, so for me `new Date(0)` is `Wed Dec 31 1969 16:00:00 GMT-0800 (Pacific Standard Time)`.  If I add or subtract months from this date, the local time will stay 16:00:00, even after daylight savings is active. But that means that the time in UTC will change by +/- 1 hour, which in turn will change the date in UTC too.

This may not be the behavior you want if you're using only UTC, but it is correct behavior for local timezone date math.

If you replace `new Date(0)` (UTC epoch) with `new Date(1970, 0, 1)` (local time) then your code above should behave as expected.

To see why `addMonths()` works correctly despite using `new Date(0)`, take a look at the implementation: 
https://github.com/date-fns/date-fns/blob/96ed50558c7e920c0fccfb732b19029ac86dcc5c/src/addMonths/index.js#L28-L42

Even though the `Date(0)` on Line 34 starts out as UTC epoch, the year/month/day is overwritten in the next line, and the time is never used, so the fact that the month is Dec 1969 in my local timezone won't break anything... at least I think it won't. But I agree with you that `Date(0)` is a dangerous pattern to use if you're doing local-timezone date math. I'd avoid it. 

BTW, if you want to use UTC for everything, then you'll have to figure out a way to set your user timezone to UTC, or to use a UTC-friendly date library like `date-fns/utc` which is (per the [docs](https://date-fns.org/v2.12.0/docs/Getting-Started#submodules)) under development.

**Comment by lolgesten** [comment]
> I believe that this behavior is NOT a bug, but is expected behavior because date-fns only uses the user time zone (which is only UTC if node's TZ is set to UTC!)

I think you are focusing too much on UTC. I believe the problem is bigger. I go back to this simple example:

```
> require('date-fns').addMonths(new Date("2017-09-01T00:00:00.000Z"), 1)
2017-09-30T23:00:00.000Z
```

The fact that it says `Z` there is not the problem. It's about user intention. When I read the above line I interpret that as:

_Create a `Date` for some point in time, and add a WHOLE one month to that._

But what it in fact does is:

_Create a `Date` for some point in time . Convert "1 month" to some offset in local timezone and add that to the original._

From a user's perspective that's just confusing. A whole month is a whole month, and as a user I never expect adding "1 month" would be 30 days and 23 hours. 

"2017-09-01" + "1 month" => "2017-10-01" regardless of timezone of the original Date or the timezone you happen to have your computer set to.

**Comment by dcousens** [comment]
@justingrant maybe a simple addition to the library would be `addUTC`?

**Comment by tanoabeleyra** [comment]
> From a user's perspective that's just confusing. A whole month is a whole month, and as a user I never expect adding "1 month" would be 30 days and 23 hours.

This. It's really confusing to use a method called `addMonth` and sometimes get the same month as output. It leads to unexpected bugs.

Also, a lot of us came from the Moment.js library (looking for a lightweight alternative) and adding a month in Moment.js works as expected.

**Comment by dcousens** [comment]
> This. It's really confusing to use a method called addMonth and sometimes get the same month as output

Can you show why you think could happen?
DST in a local timezone could result in less than expected number of hours being added,  but the local date should still be exactly incremented by 1 month.

**Comment by tanoabeleyra** [comment]
@dcousens To be honest, I don't really remember what was our use case (I'm not even working on the same project nor the same enterprise anymore), but I do remember that the way the `addMonth` method works led to a bug and we had to replace the library with Moment.js.

**Comment by justingrant** [comment]
Good discussion!  I'll try to respond to everyone in one post, hope this is OK. 

> @tanoabeleyra It's really confusing to use a method called addMonth and sometimes get the same month as output. It leads to unexpected bugs.
> Also, a lot of us came from the Moment.js library (looking for a lightweight alternative) and adding a month in Moment.js works as expected.

FWIW, the behavior described in this issue is exactly the same behavior that you'll get in moment.js, as long as the local timezone has DST that starts in March:

```js
import moment from 'moment'
const date = new moment('2019-03-01T01:00:00.000Z')
console.log(date.toDate().toISOString()) // 2019-03-01T01:00:00.000Z
date.add(1, 'month')
console.log(date.toDate().toISOString()) // 2019-03-29T00:00:00.000Z  
```

> @lolgesten From a user's perspective that's just confusing. A whole month is a whole month, and as a user I never expect adding "1 month" would be 30 days and 23 hour

Imagine you live in a timezone where DST starts in mid-March and you have an AI assistant that manages your calendar. You have an appointment on March 1 at 9:00 AM and you say: "Alexa, please postpone that appointment exactly one month". Would you expect the appointment to still be at 9:00AM?  If yes, then "one month" in that context is 30 days and 23 hours.

I'm not saying that this default behavior sometimes isn't desired. My point is that local-time is the default behavior, not just for date-fns (`import from 'date-fns'`) but also for moment.js, and `Date.setMonth()`. These are all based on a timezone-dependent definition of "month". If you use these APIs, then you'll get local-timezone behavior.

On the other hand, if you want to ignore DST and simply add exactly 31 24-hour periods to a date, then you'll need to opt-in by using an API which uses the UTC "timezone", like [`date-fns/utc/addMonths` (if it's ready)](https://date-fns.org/v2.13.0/docs/Getting-Started#submodules), [`moment().utc()`](https://momentjs.com/docs/#/parsing/utc/), or [`Date.setMonthUTC`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCMonth)

> @dcousens DST in a local timezone could result in less than the expected number of hours being added, but the local date should still be exactly incremented by 1 month.

This is correct.

> @dcousens maybe a simple addition to the library would be addUTC?

Given that there's already a `date-fns/utc` submodule, I'd suggest trying to complete and release those functions instead of adding another way to get UTC behavior.

**Comment by justingrant** [comment]
Also, IMHO the long-term answer to all these problems (other than outlawing DST which I would fully support!) is the TC39 [Temporal](https://github.com/tc39/proposal-temporal) proposal to finally add a good Time/Date API to the JS standard library. 

It's currently in stage 2 and I think the API is looking really good.  The key to making it a great API is that there are different classes used for Absolute (UTC) datetimes, local datetimes, date-only dates, time-only times, etc. This is essentially the core best practice: by specifying your use-case up front into different JS classes, it's a lot harder to accidentally mix UTC and local (or date vs. date+time) and get unexpected results. 

I'm really looking forward to being able to use that [API](https://tc39.es/proposal-temporal/docs/index.html) in the future.

![image](https://user-images.githubusercontent.com/277214/81622754-b5130c00-93a6-11ea-87ec-f1116c2211fe.png)

**Comment by tanoabeleyra** [comment]
> FWIW, the behavior described in this issue is exactly the same behavior that you'll get in moment.js, as long as the local timezone has DST that starts in March.

Ok, I might be wrong or our use case was different, but I remember that using Moment.js fixed the problem. I'm sorry I don't have a working example anymore.

Thank you so much for taking the time of writing such a detailed justification for this behavior.

**Comment by kossnocorp** [comment]
@justingrant thank you so much for chiming in!

As @justingrant noted, this is expected behavior.

**Comment by luisFebro** [comment]
[back] 2022-01-02T19:56:22.078Z
[back] 2022-02-02T19:56:22.078Z
[back] 2022-03-02T19:56:22.078Z
[back] 2022-04-02T19:56:22.078Z
[back] 2022-05-02T19:56:22.078Z
[back] 2022-06-02T19:56:22.078Z
[back] 2022-07-02T19:56:22.078Z
[back] 2022-08-02T19:56:22.078Z
[back] 2022-09-02T19:56:22.078Z
[back] 2022-10-02T19:56:22.078Z
[back] 2022-11-02T19:56:22.078Z
[back] 2022-12-02T19:56:22.078Z

Everything is working in the latest version. Mine is 2.11.0
