### ISSUE TITLE
Support milliseconds returned from Date::getTime() (in fromUnixTime or separately)

### ISSUE THREAD

**Issue by strarsis** [date-fns/date-fns#1526]
Recent `date-fns` `2.6.0` is used.

Let's take the UNIX timestamp from today (at time of writing):
```js
console.log(new Date().getTime());
````
For 01.01.2019 22:44 (approximately) this would be `1572644655083`.

Let's pass this UNIX timestamp to `date-fns`' `fromUnixTime` and log it to console:
```js
const fromUnixTime = require('date-fns/fromUnixTime');
const date = fromUnixTime(1572644655083);
console.log(date);
````
````
+051805-02-15T17:31:23.000Z
````
This can't be right as the year is way, way off.

Converting the UNIX timestamp `1572644655083` with a converter like [this online converter](https://www.freeformatter.com/epoch-timestamp-to-date-converter.html) yields 
a correct date and time (different format, but the year is right):
````
1.11.2019, 22:44:15
````

Do such large numbers as these UNIX timestamps need to be treated specially in JavaScript?
Could this be the reason for the completely incorrect conversion?

**Comment by redbugz** [comment]
I think unix time is in seconds, but `Date.getTime()` is in milliseconds. So I think you could do something like this:
```
console.log(Math.round((new Date()).getTime() / 1000))
```

**Comment by strarsis** [comment]
@redbugz: IMHO it would be a nice addition to `date-fns` `fromUnixTime` to automatically handle millisecond UNIX timestamps, or offer an option or separate method. Sure, it is just `/ 1000`, but a function that just can handle millisecond UNIX timestamps without any would be better.

**Comment by SneakyFish5** [comment]
This would be a simple change, but wouldn't it be a breaking one as well? I don't know the policy on breaking changes, could a maintainer comment on this?

**Comment by strarsis** [comment]
@SneakyFish5: Would it? When the method just checks for the precision of the passed number and takes that into account when doing the calculation (`/ 10`;  `/ 100`; `/ 1000`).

**Comment by SneakyFish5** [comment]
Currently, `fromUnixTime` takes in seconds but ironically multiplies it out to milliseconds anyways and passes that into `toDate`. To do what you ask would simply be removing the `* 1000` as far as I'm aware. This would break compatibility though, because you would now be passing in solely milliseconds, not seconds. However I don't understand what you mean by precision checking in the argument. Could you further explain that?

**Comment by leshakoss** [comment]
Guys, there's no need for that at all!

[All date-fns functions](https://github.com/date-fns/date-fns/blob/master/src/differenceInMonths/test.js#L24-L30) can receive milliseconds timestamps instead of dates. That's what [`Date|Number`](https://github.com/date-fns/date-fns/blob/master/src/differenceInMonths/index.js#L17) means in type signatures in docs.

If you just want to create a date from ms timestamp, you can use `toDate` from date-fns:

```
> const timestamp = new Date().getTime()
> toDate(timestamp).toString()
'Sun Nov 03 2019 13:56:41 GMT+0100 (Central European Standard Time)'
```

But even that is overkill since vanilla `Date` constructor also can do that:
```
> new Date(timestamp).toString()
'Sun Nov 03 2019 13:56:41 GMT+0100 (Central European Standard Time)'
```

**Comment by JanKaifer** [comment]
For googlers, relevant working links are here: https://github.com/date-fns/date-fns/blob/master/src/differenceInHours/test.ts#L75-L81

It seems that the tests are working here, but it still works for timestamps (they get converted to `Date` with `toDate`).

Sorry for bumping the old thread.
