### ISSUE TITLE
Feature request: Chain method calls

### ISSUE THREAD

**Issue by andreybleme** [date-fns/date-fns#1532]
Would be elegant in terms of manutenibility and readability to be able to write chained method calls for date-fns methods in particular situations, such as this:

```
myDate.addMonths(1).addHours(3);
```

Instead of only providing helper functions, such as we need to do right now:

```
let myDate = addMonths(myDate, amount);
myDate = addHours(3);
```

Maybe an interesting design strategy to implement this, would be to create a specific date format (just like moment.js does) and returning this special data type, instead of always working only with javascript Date type.

What do you guys think about it?

**PS:** I really like the simplicity of this library. My suggestions is just to add this flexibility as an option, not the standard. :battery:

Thank you! :)

**Comment by kossnocorp** [comment]
Hey! Thank you for your feedback!

We considered this option and came up with a solution that fits date-fns better: FP composition. So instead of:

```js
myDate.addMonths(1).addHours(3);
```

...you can (using [the FP submodule](https://date-fns.org/v2.6.0/docs/FP-Guide)):

```js
flow(addMonths(1), addHours(3))(myDate)
```

It allows keeping functions isolated that greatly affects the build size and also encourage the functional approach. These two are the cornerstones of the date-fns. I know, for some OP approach is more comforting, but for those, there're plenty of options, such as Day.js and Luxon.

I know, for some object-oriented approach is more comforting, but for those, there're plenty of options, such as Day.js and Luxon.

date-fns wouldn't date-fns if we had gone this way, so I'm closing the issue.

**Comment by kunukn** [comment]
I spend some time make this work. To share more example code, this is what works for me.

```
import flow from "lodash/fp/flow";
import { addMonths, addHours } from "date-fns/fp";

console.log(
  flow(
    addMonths(1),
    addHours(3)
  )(new Date())
);
```
