### ISSUE TITLE
How to format this string?

### ISSUE THREAD

**Issue by sclavijo93** [date-fns/date-fns#1552]
Hi! I'm really confused on how can I parse this string:

`Fri Nov 29 2019 14:44:00 GMT-0300 (Paraguay Summer Time)`

Can somebody help me, please?

Context:
I'm using material-ui/pickers, formik and Yup and I would like to test if a date is after or before another date. This is the code I'm working on:
```
.test("testing-dates", "The date is incorrect", function(value) {
console.warn(value);
console.warn(this.resolve(ref("active_to")));
            return isAfter(value, this.resolve(ref("active_to")));
          })
```

This is the output in the console:
```
Fri Nov 29 2019 14:56:00 GMT-0300 (Paraguay Summer Time)
"Sat Nov 30 2019 14:56:00 GMT-0300 (Paraguay Summer Time)"


Starting with v2.0.0-beta.1 date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings.
```

**Comment by fturmel** [comment]
If anyone is still stuck with a similar issue, this format looks like the output of a JS Date's `toString()` method.

In `date-fns` v2, functions do not accept strings anymore, only Date or a timestamp (ms since ECMAScript epoch). This string format is also not [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compatible, so `parseISO` would not be able to understand it.

Maybe there is a Date to string type coercion/conversion happening in your code somewhere that you can get rid of?

If you have to work with that string value, you should be able to safely feed it back to a Date constructor and create a new Date instance.

Tested in Safari, Firefox and Chrome:

```js
import { isAfter } from "date-fns";

// rebuild the date
const date = new Date(
  "Fri Nov 29 2019 14:44:00 GMT-0300 (Paraguay Summer Time)"
);
console.log(date.toString()); // Fri Nov 29 2019 12:44:00 GMT-0500 (Eastern Standard Time)
console.log(date.toISOString()); // 2019-11-29T17:44:00.000Z

// check if the date is after Jan 1st 2010 (local time zone)
const earlierDate = new Date(2010, 0, 1);
console.log(isAfter(date, earlierDate)); // true

// you can also do greater/smaller than comparisons directly with Date objects in JS
// https://stackoverflow.com/questions/492994/compare-two-dates-with-javascript
console.log(date > earlierDate); // true
```
