### ISSUE TITLE
formatISO omitting final `Z` character in dates

### ISSUE THREAD

**Issue by aryzing** [date-fns/date-fns#1559]
An ISO date should have either a time offset or `Z` appended to the end. Omitting this `Z` character causes the date as being relative to the host machine's timezone. When performing operations across time zones, this is problematic.

**Comment by jpodpro** [comment]
just noticing this too. isn't the whole point of iso8601 that it must have a time-zone specified also?

**Comment by Imballinst** [comment]
Hmm, back then we only took the date, time, and datetime as the scope (see http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm). We can add timezone if it is needed.

I think the reason we thought that it was okay to omit timezone because ISO8601 is mostly in UTC (?) cc: @leshakoss

**Comment by kossnocorp** [comment]
I believe the full output should contain the timezone. I didn't think about that when I was looking at the PR. Not sure how it fits the API though.

**Comment by Imballinst** [comment]
I can work on this issue, this weekend.

**Comment by cyberwombat** [comment]
Perhaps along the same lines - doesn't seem possible to use format with UTC either. See this SO post https://stackoverflow.com/questions/58561169/date-fns-how-do-i-format-to-utc
