### ISSUE TITLE
I get different results between Moment and Date-fns for the same date string

### ISSUE THREAD

**Issue by simkessy** [date-fns/date-fns#1656]
I have this date string: `2020-01-21` and I get two different results between Date-Fns and Moment: 

         Date-fns: {format(new Date(startTime), 'MMM d, y')} => Jan 20, 2020
          Moment:  {moment(startTime).format('MMM Do, YYYY')} => Jan 21st, 2020

**Comment by noahcho** [comment]
what version were you using?

**Comment by Imballinst** [comment]
From a quick hunch, it's probably  because of timezone, as your date string doesn't specify time and time zones. For example:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/7077157/76155214-5e295600-611b-11ea-8c77-cd37af768980.png">

Could you try for the Moment part this instead?

```js
moment(new Date(startTime)).format('MMM Do, YYYY')
```

**Comment by simkessy** [comment]
using parseISO solved it for me
