### ISSUE TITLE
Add gives faulty result shortly after DST transition

### ISSUE THREAD

**Issue by JMillcamp** [date-fns/date-fns#1682]
Starting out with a Date within an hour after the DST transition from summer time to standard time, when adding a duration using `add` for which the result should be a Date an hour after the DST transition, the result is actually the Date immediately after the transition.

Encountered using v2.11.0 for Dutch DST at 27-10-2019 03:00 GMT+2 to 02:00 GMT+1:

```
// Each variable in the following code is set to 
// 'Sun Oct 27 2019 02:00:00 GMT+0100 (Central European Standard Time)'

let d0 = add(new Date(2019, 9, 27, 2, 0, 0), { hours: 1 });
let d1 = add(d0, { hours: 1 }); 
let d2 = add(add(d0, { minutes: 30 }), { minutes: 30 }); 
```

Using `addHours` does not result in the same behaviour.

**Comment by bohdan-shulha** [comment]
Just got the same issue. Everything is up-to-date, but it doesn't count the DST.

I use `date-fns-tz/zonedTimeToUtc` like this (AFAIK it uses date-fns under the hood to get offsets):

```
> fns = require('date-fns-tz')
> utcTime = fns.zonedTimeToUtc(`2020-01-01 09:00:00`, 'Europe/Kiev')
2020-01-01T07:00:00.000Z // should be 06:00:00 by the time of writing)
```

**Comment by justingrant** [comment]
I think I understand why this bug is happening.  The root cause is likely in the `addMonths` function (which is called by `add` even when `months` is zero or omitted).

When `addMonths` is passed a time in the ambiguous hour before the end of DST, it will mutate that time to the DST version of the same time, even if the desired increment is zero months.  `add`, in turn, calls `addMonths` with a zero increment and therefore mutates the time to one hour earlier before applying the `hours` or `minutes` increments which add that hour right back to where you started. Which I believe matches the repro behavior that you found. 

I suspect the easiest fix would be to simply return early in `addMonths` when the `amount` isn't nonzero. I haven't tested this so YMMV. Something like this:

```js
export default function addMonths(dirtyDate, dirtyAmount) {
  requiredArgs(2, arguments)

  var date = toDate(dirtyDate)
  var amount = toInteger(dirtyAmount)
  if (!amount) {
    // If 0 months, no-op to avoid changing times in the hour before end of DST
    return date
  }
  . . .
```

Here's more details about the problem if you're curious.

Here's the rest of the code of `addMonths`: 
https://github.com/date-fns/date-fns/blob/2a146aa973c0ab075eca3f27c7c8cee61093b39b/src/addMonths/index.js#L33-L41

`setFullYear` and/or `setHours` convert local times to UTC. This triggers a specific behavior defined in the ECMAScript spec for how to handle ambiguous times like the hour before DST ends in the fall. During these "ambiguous local time" periods, the same local time can correspond to two different UTC times: one in DST and one not. In those cases, here's what the [spec](https://tc39.es/ecma262/#sec-local-time-zone-adjustment) says must happen: 

> When `tlocal` represents local time repeating multiple times at a negative time zone transition (e.g. when the daylight saving time ends or the time zone offset is decreased due to a time zone rule change) or skipped local time at a positive time zone transitions (e.g. when the daylight saving time starts or the time zone offset is increased due to a time zone rule change), `tlocal` must be interpreted using the time zone offset before the transition.

Anyway, `addMonths` calls `setFullYear` and `setHours` which convert local time into UTC and hence trigger the paragraph above from the spec. This means that any ambiguous local times passed into `addMonths` will be converted to the earlier (DST) version of that local time, which is one hour earlier than the winter-time version of that same local time.  With this knowledge, let's look at your repro code: 

```js
let d0 = add(new Date(2019, 9, 27, 2, 0, 0), { hours: 1 });
```
Per the spec, this local date is resolved to the DST (earlier) version of this ambiguous time. Then it's passed to `add`, which in turn passes it to `addMonths`, which doesn't do anything because it's already the DST (earlier) version of this local time. Finally, `add` adds one hour which results in the non-DST (later) version of this local time. 

```js
let d1 = add(d0, { hours: 1 });
```
Here the argument to `add` is one hour later than the line above. But when `add` calls `addMonths`, the time will be mutated to one hour earlier, to the DST version of this local time. Then, like with the first call, `add` adds an hour to get back to the non-DST 2:00. 

```js 
let d2 = add(add(d0, { minutes: 30 }), { minutes: 30 }); 
```
Here, the inner call will result in DST 2:30 using the same flow as the line above. Because the inner call's result is already a DST time, the outer `addMonths` call (in the outer call to `add`) will not change the time before it adds 30 minutes to yield non-DST 2:00.

**Comment by justingrant** [comment]
I just filed PR #1760 to fix this issue.

**Comment by zuzusik** [comment]
while `add` seems to be fixed by https://github.com/date-fns/date-fns/pull/1760, `sub` is still affected by this issue
