### ISSUE TITLE
parse("1586195963531") returns Invalid Date

### ISSUE THREAD

**Issue by SephReed** [date-fns/date-fns#1716]
Sometimes `Date.now()` gets passed to a database, then turned into a string.  In such a case, parse will fail.

Here is the code I must use:
```
const dbItem = { birthday: String(Date.now()) };
let date;
try {
  date = parse(parseInt(dbItem.birthday));
} catch(err) {
  date = parse(dbItem.birthday);
}
```

This is what could be done with an update to parse:
```
const dbItem = { birthday: String(Date.now()) };
const  date = parse(dbItem.birthday);
```

**Comment by dkozickis** [comment]
`parse` accepts `string` as first argument by design, what is your proposal exactly here please?

**Comment by kossnocorp** [comment]
This is a kind of behavior we avoid to prevent obscure bugs. For example, if you pass `2020` or `20200101`, how should we parse it?

I'm not familiar with your context, but it seems that the real problem is that you store inconsistent data in your database. I would recommend trying to fix that first and if for some reason it's impossible, stick to the `parseInt` hack.

Btw, your code snippet in the issue description is prone to errors too because `parseInt('2020-01-01')` will return `2020`.

**Comment by SephReed** [comment]
> Btw, your code snippet in the issue description is prone to errors too because parseInt('2020-01-01') will return 2020.

Thank you very much.  I totally forgot parseInt does that.

> For example, if you pass 2020 or 20200101, how should we parse it?

Yeah, I see the issue there.

Do you think there's somewhere else where handling `Date.now() + ""` might occur in date-fns?  The fact that parseInt() is so unsafe around it seems like even more the reason it shouldn't be a roll your own kind of date function.

> it seems that the real problem is that you store inconsistent data in your database. I would recommend trying to fix that first...

One does not simply.
