### ISSUE TITLE
Parse ignores reference date

### ISSUE THREAD

**Issue by no0by5** [date-fns/date-fns#1741]
The documentation for parse date says: defines values missing from the parsed dateString
So if I run this code, I would expect to get the date `Sat Dec 11 2002 01:02:00`.
``` js
const reference= new Date("2021-12-11 01:02");
console.log(parse("02", "yy", reference));
```
But actually I get the date `Tue Jan 01 2002 00:00:00`.
Is this the intended behaviour, and did I just misunderstand the documentation or is there a bug?

**Comment by kossnocorp** [comment]
Yes, this is intended behavior.

At some point, I wanted to use reference data to fill missing values as you excepted. However, it turned out to be worse behavior than it is now. The issue here that people usually use `Date.now()` as the reference data, so when they parse `parse('2020-02', 'yyyy-MM', Date.now())` and get `"2020-02-24T09:39:01"` instead of `"2020-02-01T00:00:00"` they get confused. Furthermore, there're tons of edge cases, so we decided to keep the current behavior.

There're few approached to your problem but it depends on what you're trying to do. If you want help, please describe your use case in detail and I will suggest a solution.

**Comment by no0by5** [comment]
In this case, you should probably update the documentation.
Does the reference date now have any function?

In my case I have a date picker and a time picker that update the same Date object. When I use the date picker, I only want to update the date value and use the old time value from the Date object and vice versa.
Thank you for your help!

**Comment by akloyal** [comment]
What's the point of mandatory referenceDate? what if we parse date of birth?

**Comment by dimitri-HR** [comment]
Thank you for the great library but I have to agree... 
It's not really clear how `referenceDate` is suppose to work and because it's mandatory, just seems to add to confusion ;-)

What are these missing part that would be added - day, month, year? hours, minutes, seconds? timezone?
What if my date is deep in the past (e.g. 500 year ago) - do I still need to provide a reference date? 
What should it be? A current date `new Date()`?
If I don't have any missing parts in my date - why provide the referenceDate at all? 

Maybe this parameter should be optional.
And it would be great to have more examples on how to use it
