### ISSUE TITLE
parseISO - parsing invalid string into a valid date

### ISSUE THREAD

**Issue by MBelniak** [date-fns/date-fns#1748]
Hi.
I've come across this issue while using date-fns. 
Current behaviour:
`parseISO('2016-03-16T08 ooo') // returns Date(Wed Mar 16 2016 08:00:00 GMT+0100 (CET))`
Expected behaviour (at least momentjs and some online regex-based parsers):
`parseISO('2016-03-16T08 ooo') // returns Invalid Date`
Is this actually a bug or for some reason current bahaviour is the expected one?

**Comment by Imballinst** [comment]
@kossnocorp is this intended behavior? From a quick glance on `parseISO`, it uses RegEx to parse the date and time. I think in this case, it only "partially parses" the invalid string. CMIIW!

**Comment by kossnocorp** [comment]
I've no strong opinion regarding this, to be honest. As I see, not only Moment.js behaves like that:

```js
new Date('2016-03-16T08 ooo')
//=> Invalid Date
Date.parse('2016-03-16T08 ooo')
//=> NaN
```

So I guess this is a bug.

**Comment by Imballinst** [comment]
Alright, thanks for the clarification! I'll try attempting on this issue.

**Comment by kossnocorp** [comment]
@Imballinst thanks 🙏

**Comment by Imballinst** [comment]
@dojchek noted -- thanks for the information! I'll try handling that case as well in my PR.

**Comment by Imballinst** [comment]
@dojchek it seems like the 2 digits are used to represent centuries, so I guess that's intended?

https://github.com/date-fns/date-fns/blob/4cf918f6e66499ced4254decf3573bf365e871c8/src/parseISO/test.js#L103-L120

CMIIW @kossnocorp

**Comment by dojchek** [comment]
@Imballinst Yes, I also think that's intended - although not very intuitive..
I found only one reference to this format in wiki article which says:
`One may simply write "1981" to refer to that year or "19" to refer to the century from 1900 to 1999 inclusive`

So it is in fact a valid ISO date. I still need this to "fail" in my use case - so I will check it with some regex or simply check the length of string before doing parseISO, since I only work with dates like `2020-06-26` and `2020-06-26T04:33:26+00:00`.

Thank you very much for checking this out
