### ISSUE TITLE
parseISO bug in Chile due timezone change

### ISSUE THREAD

**Issue by raerpo** [date-fns/date-fns#1939]
Hi, since september 5 2020 there was a timezone change on Chile from GTM-4 to GTM-3.

I noticed that everything worked as expected on almost every device but for iPhone and Safari it keeps showing the wrong timezone.

Screenshot on firefox with correct timezone
<img width="1349" alt="firefox" src="https://user-images.githubusercontent.com/1649463/92330958-535b6980-f049-11ea-9cbc-0655df5cd08e.png">

Screenshot on safari with incorrect timezone
<img width="1354" alt="safari" src="https://user-images.githubusercontent.com/1649463/92330963-56565a00-f049-11ea-9c89-f030273e2e36.png">

This is the codesandbox in which you can reproduce the issue:

https://codesandbox.io/s/date-fns-issue-w320l

Thanks!

**Comment by MyIsaak** [comment]
Are you testing on the same device, or is this a desktop and a mobile phone? Could be an issue outside of date-fns. Have you tested this with another date parser, such as the default `(new Date()).toISOString()`?

**Comment by raerpo** [comment]
I tested it on the same device with differente browsers (firefox and safari) also with an Android (chrome) and iOS (chrome and safari) and the results are the same as the original issue.

I tested it using `(new Date()).toISOString()` and the results for that line is the same on both browsers so that's why I'm thinking the problem is related with date-fns.

I updated the codesandbox with your suggested parser

**Comment by MyIsaak** [comment]
I can't replicate this issue.

![image](https://user-images.githubusercontent.com/4984415/92384956-4c982980-f111-11ea-974e-115c4e342df9.png)

**Comment by raerpo** [comment]
That's what I was afraid. But shouldn't date-fns compensate in some way this kind of issues with timezones?
Just to know if this is something that should be address here or maybe just report it to Apple and you we can proceed to close this issue :) 

Thanks for responses

**Comment by MyIsaak** [comment]
I wonder that too, since `date-fns` sells that it works with all timezones. But on the other hand, you can't go around this without knowing the correct timezone via the browser in the first place. Perhaps that's a key limitation of this library, one should consider.

My alternative approach would be to modify the existing date library's timezone with one received from a trusted (or configurable) NTP server. But then again, modifying the Date object is outside this project's goals i think.

**Comment by vcanales** [comment]
There's a difference in how Safari parses dates when no hours are given apparently. Using full timestamps on Zulu Time generates the correct output for all browsers:
https://codesandbox.io/s/date-fns-issue-forked-zj07o?file=/src/index.js

**Comment by systemride** [comment]
We just ran into this issue again this year. On September 3, 2023 the timezone of America/Santiago (Santiago Chile) adjusted their daylight savings at midnight. This doesn't have to do with Safari as you can reproduce this issue in a node or mobile environment.

Here's a breakdown of what happens:

At the start of DST, the clocks go forward one hour at midnight. This means:
- Midnight at the end of September 2nd (24:00) instantly became 01:00 on September 3rd.
- Therefore, the entire hour from 00:00 to 00:59 on September 3rd never occurred in local time!

The reason this matters is because if you give parseISO a date with no time, eg: `parseISO("2023-09-03")` it will default to midnight. But because of what I explained above, midnight on Sep 3rd in this timezone does not exist so this will create a date as the following:
```
2023-09-03T03:00:00.000Z
```
And when you call this date with `date.toString()` you will get:
```
Sat Sep 02 2023 23:00:00 GMT-0400
```

As a workaround, we've been passing in a time of 12 noon local time like so:
```
parseISO("2023-09-03T12:00:00")
```

However, I think that `date-fns` should be handling these cases. I would expect that passing in a date of `2023-09-03` should always give me back September 3rd.

Also, [there are a handful of timezones/countries](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country) that have daylight savings time changes that take place at midnight.

**Comment by systemride** [comment]
Looks like this is actually a hermes issue:
https://github.com/facebook/hermes/issues/1121

**Comment by harogaston** [comment]
That is the responsability of the engine/OS or whatever ultimately provides wall clock access. This is not the scope of the library, there is now way possible to keep up-to-date timezone information in our code, that is what OSs or runtimes should do. You can open a bug report with them if you feel like.
