### ISSUE TITLE
Add an ability to pass a locale object to distanceInWords function

### ISSUE THREAD

**Issue by simonsmith** [date-fns/date-fns#203]
Hey,

I need to customise the text used in `distanceInWordsToNow` but I noticed the `locale` object is [private to the module](https://github.com/date-fns/date-fns/blob/master/src/distance_in_words/index.js#L174-L226). Could this be exposed, or allowed to be changed via the options?

Thanks

**Comment by montogeek** [comment]
I think this will be available once the library supports i18n

**Comment by kossnocorp** [comment]
@simonsmith @montogeek right, since v1.0.0 is released, I18n is our top priority.

**Comment by ryyppy** [comment]
Would be cool to have a whole `translate` function instead of data structures!
For the functional part, are there any plans to do a data-parameter-last approach?

Anyways I would be in for that.

**Comment by kossnocorp** [comment]
@ryyppy can you elaborate your `translate` function idea? 

It's not final, but I had such API in my mind:

```js
distanceInWords(new Date(2015, 0, 1, 0, 0, 15), {
  // Re-use options object, so:
  //   1. Less arguments
  //   2. Consistent with the current API (distanceInWords already have
  //      the options argument).
  locale: {
    // Use single locale object for all functions:
    //
    //   var format = require('date-fns/format')
    //   var jp = require('date-fns/locale/jp')
    //
    //   function jpFormat (date, formatStr) {
    //     return format(date, formatStr, {locale: jp})
    //   }
    //
    //   function jpDistanceInWords (date, options) {
    //     return distanceInWords(date, Object.assign({}, options, {locale: jp}))
    //   }
    distanceInWords: {
      lessThanXSeconds: {
        // A locale string could be a string
        one: 'less than a second',
        // ... or a function
        other: ({count}) => `less than ${count} seconds`
      },

      // ...
    },

    format: { /* ... */  }
  }
})
```

To keep functions "pure" (as pure as date functions could be 😆 ) and prevent build bloating,  the recommended approach would be to use own/3rd-party wrappers, e.g.:

```js
var format = require('date-fns/format')

var locales = {
  en: require('date-fns/locale/en'),
  jp: require('date-fns/locale/jp'),
  ru: require('date-fns/locale/ru')
}

module.exports = {
  format: function (date, formatStr) {
    return format(date, formatStr, {
      locale: locales[window.__localeId__]
    })
  },

  // ...
}
```

I still thinking about the best approach, so any input would be helpful.

Regarding "data-parameter-last approach". While it's native to languages like Haskell:

```hs
todayDate = -- Some code

isSameDate dateA dateB = 
  -- Some code 

isToday date = isSameDate todayDate
```

In my opinion it's ok to have such code in JavaScript (partially because of last-parameter-options approach):

```js
const isToday = (date) => isSameDate(date, new Date())
// vs
const isToday = isSameDate.bind(new Date()) // Will became a pumpkin after midnight
```

**Comment by ryyppy** [comment]
@kossnocorp Your draft looks really promising! I was writing some functional conversion libs myself lately and usuallly ended up writing functions which deferred formatting to the very last instance and only  programmatically by the user...

So I would rather let `distanceInWords` return a data-structure describing the data to format ({ token: 'lessThanXSeconds', count: 100 }) and then involve a specifically localized `format` with that data, instead of mixing in the format function right away...

This would also motivate the reason why data-last would be more practical... since you can easily `compose` those decoupled functions later on...

```
// Just use any cheap compose function
import { compose } from 'lodash/fp';
import { distanceInWords } from 'date-fns';

// Really naive prototype... we couple this localization map to the format function
const localization = {
  de: {
    lessThanXSeconds: "vor %d Sekunden"
  }
};
const format = (locale, { token, count }) => localization[locale][token].replace("%d", count);
const deFormat = (arg) => format("de", arg);

// E.g. could return { token: 'lessThanXSeconds', count: 100 }
// const tokenAndCount = distanceInWords(new Date(2015, 0, 1, 0, 0, 15));

// So now as a end user, we lego-build our stuff together how we need it
const myLocalizedDistanceInWords = compose(deFormat, distanceInWords);

// This would return "vor 100 Sekunden"
myLocalizedDistanceInWords(new Date(2015, 0, 1, 0, 0, 15));
```

Each function does exactly one thing very well, which makes it very easy for composition and for testing.

I mean, this is probably a no-go anyway, since the API has a completely different style, .. but still... I had a lot of advantages when I decoupled the formatting from the data processing itself.

It's quite late and I maybe went off-topic... I still post this in the hope you or someone else gets inspired by this :^)
