### ISSUE TITLE
Problem to format date "2020-10-23:00:00+00:00"

### ISSUE THREAD

**Issue by gabrielgrs** [date-fns/date-fns#2107]
Hello people!

I'm trying to format the following date:
"2020-10-23:00:00+00:00"
using format as this way:
format("2020-10-23:00:00+00:00", "dd/MM/yyyy")

The problem is that he ends up returning 3 hours, because of the time zone. Is there a way for me to ignore the timezone and return only the value of the formatted date?

```javascript
const formatToDefaultDate = (date) => {
  return format(new Date(date), "dd/MM/yyyy");
};

console.log(formatToDefaultDate("2020-10-23:00:00+00:00"))
// output: 22/10/2020
```

**Comment by levymetal** [comment]
I feel like this is something [date-fnz-tz](https://github.com/marnusw/date-fns-tz) should handle, but it doesn't.

The way I've solved this is to strip the offset from the string. This effectively prevents any conversion as without an offset the browser assumes the date is already in the local timezone. If you want maximum compatibility you should also use `parseISO` due to inconsistent behaviour of the `Date` constructor.

For example:
```js
export function parseZone(date: string): Date {
  if (date.length <= 10) return parseISO(date);
  return parseISO(date.replace(/[+-]\d\d(:?\d\d)?$|Z$/g, ''));
}
```

As this changes the underlying moment beware using it for comparisons. Also, if you want to print the timezone you're fresh out of luck.

Despite being a simple piece of code, I've been thinking of releasing a package because this seems like a pretty standard requirement that none of the vanilla-centric packages support. Maybe I just haven't been looking in the right place?

Note: I haven't written tests for this code (yet) so make sure to sanity check it first.
