### ISSUE TITLE
date-fns still support with bower?

### ISSUE THREAD

**Issue by mnosuk** [date-fns/date-fns#2144]
I install date-fns 2.1.16 by bower.

i get the folder

date-fns
 -> src
     -> index.js

I try to import  this index file to <script link="......index.js">
in index file 

look like we have import that javascript cant read.

how should I fix that?

**Comment by mnosuk** [comment]
the code from  bower is not transpile

I got something like export/import

how should I use with the older version of javascript?

**Comment by fturmel** [comment]
Hi @mnosuk,

Late reply, but the v2 changelog explicitly states that Bower is no longer supported.

https://github.com/date-fns/date-fns/blob/005a808f0d3b0ec18e35e7fb5be6612bd10eafc4/CHANGELOG.md?plain=1#L1188

> - **BREAKING**: The Bower & UMD/CDN package versions are no longer supported.

You should either stick with v1 for legacy projects, or modernize your dependencies and build system, especially since Bower itself has also deprecated for a while. https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Good luck!
