### ISSUE TITLE
Support ES5 destruct import

### ISSUE THREAD

**Issue by alex3165** [date-fns/date-fns#216]
Do you guys plan to support destruct import, something like :

```
import { addDays, format } from "date-fns";
```

I can do it if you want.

**Comment by alex3165** [comment]
Sorry it's working but it's not on your documentation.

**Comment by kossnocorp** [comment]
@alex3165 we can add it to docs, but it has side effect (when such syntax is used with webpack/Browserify without enabled tree-shaking then it will include **whole** library instead of just function), so I won't to add it here:

![](http://i.ncrp.co/0D330W0J0J2b/date-fns_-_modern_JavaScript_date_utility_library.png)

So, you can help us if you'll tell where you was looking (or wish to see) for this information.

**Comment by fxck** [comment]
There are no typings for this, so how exactly does it work?
