### ISSUE TITLE
Flow "unexpected token ." error

### ISSUE THREAD

**Issue by stevoland** [date-fns/date-fns#218]
I get Flow (0.27.0) errors when including date-fns in my project

```
> flow check

node_modules/date-fns/add_days/index.js.flow:3
  3: declare module.exports: (date: Date|string|number, amount: number) => Date
                   ^ Unexpected token .

...etc
```

Any ideas?

**Comment by jameshopkins** [comment]
You'll need to add an entry to your `.flowconfig` `[ignore]` directive that excludes these type declarations. In this case, something like `.*\.js.\flow` should suffice.

**Comment by stevoland** [comment]
Thanks, I'm already ignoring them. But I wonder why I cant use them. They would be useful.

**Comment by kossnocorp** [comment]
@stevoland I do not use Flow in my day-to-day development, so I can't say for sure what's the problem. However, I'm working on an investigation. Thank you for reporting!

**Comment by jameshopkins** [comment]
@stevoland are you ignoring `*.js.flow` files specifically?

Since `flow check` recursively checks [all your project code](https://flowtype.org/docs/advanced-configuration.html#ignore) (including `node_modules`), it appears `flow check` is type checking type definitions provided by `date-fns` - which happen to be in the same directory as the source methods themselves - which is a really nice touch, I think 👍 

> But I wonder why I cant use them. They would be useful.
You can use them in your project, by [importing them](https://flowtype.org/blog/2015/02/18/Import-Types.html#enter-import-type)

**Comment by kossnocorp** [comment]
Hey! I'm closing the issue. We're going to address this in https://github.com/date-fns/date-fns/issues/244

**Comment by ChirappaVishnupriya** [comment]
Hi 
I am using nb-rangepicker with format="MMMM dd, YYYY"
it comming correct for English(en( locale but not for spanish (es).

@nebular/date-fns : 6.2.3 i am using
