### ISSUE TITLE
Documentation Suggestion: provide a way to try out the library in the browser

### ISSUE THREAD

**Issue by paustint** [date-fns/date-fns#2201]
One thing I liked about the moment.js docs is that I could open the JS console on the docs page and try out the library right there as I was reading the docs since moment was provided as a global variable on that page.

With `date-fns` I have to spin up Quokka (or alternative) or try things in my codebase as I figure out the arguments for any given function or to figure out the format that I want.  For example, I can never remember the order of the arguments for isBefore and want to quickly do a sanity check before including in my codebase.

It would be great to have a playground with date-fns pre-loaded and easy to use. Even a simple external link to an online editor (e.x. code blitz) that is setup and ready to go would be sufficient.

Side note: It would also be convenient to have more examples of common formats on `format` page so I don't have to put in as much effort when I need to format a date.

**Comment by tolmasky** [comment]
If the authors are receptive to it, I'd be happy to RunKit-ify all the examples on the site like we did for [expressjs.com] (http://expressjs.com/en/starter/hello-world.html) and [immutable-js.github.io](https://immutable-js.github.io/immutable-js/):

<img width="829" alt="Screen Shot 2021-02-17 at 8 07 03 PM" src="https://user-images.githubusercontent.com/23753/108304050-0503d800-715c-11eb-833c-69490f8b953c.png">

The code lives on the page (it's not an externally linked thing like github snippets, so changes are managed completely in the source repo), users can require any other library on npm so they can tinker away, and it gracefully degrades to "non-running" code like is there now. date-fns can be assigned to "_" as well so that you don't have to require it in every box (immutable does this on their main documentation page).

<img width="717" alt="Screen Shot 2021-02-17 at 8 11 33 PM" src="https://user-images.githubusercontent.com/23753/108304210-5dd37080-715c-11eb-80df-f580c041dfc8.png">

**Comment by Andrew1431** [comment]
![image](https://user-images.githubusercontent.com/9736372/109428254-4a2dd280-79c4-11eb-9153-9a34484b769d.png)


Do you not get this prompt in the browser?

**Comment by paustint** [comment]
🤣  - I had not looked in the console for a very long time and did not realize this feature already existed.

**Comment by tan75** [comment]
Hi all, 
it looks like I can close this issue.

**Comment by tasmanboat** [comment]
https://date-fns.org/v3.6.0/docs/CDN 
here are useful info if you wish to test functions in jsfiddle.
