### ISSUE TITLE
Issue with intervalToDuration on 28 of february and utc offset

### ISSUE THREAD

**Issue by pmogollons** [date-fns/date-fns#2289]
The issue is apparently only happening on this date (28 of feb) and when using an utc offset. I have this reproduction tested in isolation and it fails returning the following interval.

```javascript
{
  days: 27
  hours: 1309
  minutes: 157118
  months: 1
  seconds: 18854179
  years: 0
}
```

This is the reproduction for the bug.

```javacript
import intervalToDuration from "date-fns/intervalToDuration";

console.log(
  intervalToDuration({
    start: new Date('2021-02-28T08:00:00-05:00'),
    end: new Date('2021-02-28T18:21:41-05:00')
  })
);
```

**Comment by tan75** [comment]
Hi @pmogollons 
Thanks for pointing this out.
The fix for this issue is going to be available in our nearest release - please see 
https://github.com/date-fns/date-fns/issues/2255
The PR for the fix is here: 
https://github.com/date-fns/date-fns/pull/2256

I am going to close this issue to minimise the amount of duplicates.
