### ISSUE TITLE
How to convert duration to human-readable?

### ISSUE THREAD

**Issue by edouard-lopez** [date-fns/date-fns#229]
Hi,
can I use `date-fns` to format an `uptime` (_e.g._ `176347295`) in a human-readable format (e.g. `x days y hours z seconds` )?

**Comment by kossnocorp** [comment]
@edouard-lopez it's kind-of-possible with [`distanceInWords`](https://date-fns.org/docs/distanceInWords) or [`distanceInWordsToNow`](https://date-fns.org/docs/distanceInWordsToNow), but it won't be such precise (e.g. it will give you `4 weeks` or `3 days` or `a minute` and so on). If it doesn't work for you, we can consider adding a new feature. If so, what's API you expect?

**Comment by edouard-lopez** [comment]
Wow, implementing just for me, that's so nice :smile: 

I don't really know your API, but I searched your doc for (in this order): `unix`, `epoch`, `elapsed` ;
The following might come to mind: `humanReadable`, `unixToHuman`, `elapsedTime`, `human`

**Comment by janjachacz** [comment]
I would definitely use something like **distanceFormat(dateFrom, dateTo, format)**

**Comment by kossnocorp** [comment]
Ok, will do! However, I can't say exact ETA because we're focused on I18n right now.

**Comment by tomspeak** [comment]
Are there any temporary work arounds? All my timestamps are unix, using `distanceInWordsToNow` returns `almost 47 years` ;)

**Comment by LeshaKoss** [comment]
@tomspeak try multiplying timestamps by 1000

**Comment by tomspeak** [comment]
Exactly the workaround I needed, thank you! Really enjoying the library. Very lightweight.

**Comment by rickmed** [comment]
why not merge distanceInWordsStrict into distanceInWords and add a options to the options object to whatever format supported.

**Comment by robodude** [comment]
I'd be interested in this sort of feature. It'll be interesting to implement and keep the api clean.

I'd wan't something with the flexibility to control how things render. A common use case for me is putting these 'distances' in a table column, so I'd like for them to look nice.

```
distanceFormat(dateFrom, dateTo, {

    units: ['minutes', 'seconds', 'milliseconds'],

    format({ minutes, seconds, milliseconds }){
        
        // 04 mins 10 secs 620 milli ago
        return `${minutes.toString().padStart(2, "0")} mins ${seconds.toString().padStart(2, "0")} secs ${milliseconds.toString().padStart(3, "0")} milli ago` 

    }

})
```

**Comment by ndelvalle** [comment]
Any news about implementing an exact human-readable difference? 🙂

**Comment by kaermorchen** [comment]
I have my custom solution

```js
const result = [];
const now = new Date();
let future = addDays(now, 500); //add 500 days

const years = differenceInYears(future, now);
if (years > 0) {
  result.push(`${years} years`);
  future = subYears(future, years);
}

const months = differenceInMonths(future, now);
if (months > 0) {
  result.push(`${months} months`);
  future = subMonths(future, months);
}

const days = differenceInDays(future, now);
if (days > 0) {
  result.push(`${days} days`);
}

return result.join(' '); //1 years 4 months 13 days
```

**Comment by beejei** [comment]
This is really important to replace moment.js for our side.
Additionally '.format' method also needed

**Comment by danielo515** [comment]
Still not on the roadmap ?

**Comment by anyayunli** [comment]
Still not on the roadmap ? +1

**Comment by tomvibes** [comment]
Date-fns **v2** is in pre-release right now. Is there a native way in this release to get a human-readable date format like **_in 1 year 3 Months 2 Weeks 3 days 2 hours_**?

**Comment by cosimochellini** [comment]
I think that this is the link https://date-fns.org/v2.0.1/docs/formatDistance (maybe)

**Comment by CesarBMartinez** [comment]
Any news guys?

**Comment by SneakyFish5** [comment]
I've been working on a function for this and here's what I've got so far: https://github.com/SneakyFish5/date-fns/commit/e8cc4fa9345d92df91652bc5fb70eea01ace22fb

I took a lot of the feedback here to make this function and tried to use as little overhead as possible so I didn't import anything but tried to use my own math (which is imperfect as I'll show later on).

Basically the function goes `distanceFormat(dateFrom, dateTo, format)`. The first two parameters are simple, it is the two dates you want to compare. Then the milliseconds between the two dates are calculated using `getTime()`. The third parameter, format, is optional and takes in an array of units like `['year', 'month', 'days']` etc, but you can mix and match so you can have `['months', 'hours', 'milliseconds']` and so on. It will always use the first element you give it as the first unit in the returned string and divide into the smaller units that you provide afterwards.

To get into the actual function itself and how it works. Initially, it checks if format was passed in or not. If not it defaults to dividing down from seconds so that the string looks something like https://github.com/date-fns/date-fns/issues/229#issuecomment-520176824. However, if the format parameter is included, then it divides the total milliseconds into the conversion factor of the first array and then so on for the rest of the elements. E.g. if 'months' was the first element in the format array, the total milliseconds would be divided by `2592000000`.

Now there is one problem I've noticed and that is specifically to do with how I calculate months. Since months can have 30 or 31 days depending on the month, sometimes it results in an extra day. If anyone has a better system for calculating on it or if that's alright then do let me know.

I hoped I explained it well, and if anyone has any feedback or questions don't hesitate to ask/tell me since I know a lot of improvements could be made.

**Comment by polarathene** [comment]
Really wanted to give `date-fns` a try but this was a needed feature. I did not find a way to get duration as an object like `luxon` can provide.

I saw @kaermorchen 's example snippet above and thought I could reduce the method duplication down and drop the plural `s` from string if it's only 1 of unit. Looking over `date-fns` docs getting an object of the duration/interval values seems not possible?

I've got `luxon` code equivalent below, so if anyone works on this feature for `date-fns` perhaps it'd be useful if they can also get the duration broken down like `luxon` can provide.

An interval is used so that conversion to a duration object of only the units you're interested in can be properly converted if there is time nuisances involved(which a duration object would no longer be aware of as @SneakyFish5 points out with days in a month for example(but also timezones, DST, leap years etc). `luxon` offers a `diff()` method that can be used instead to get a duration between two dates as well, which is fine if there is no further modification/math on the duration object(otherwise use an interval).

```JS
const {DateTime} = require('luxon');

const formatUnit = (unit, num) => {
    const maybePlural = num > 1 ? unit : unit.slice(0, -1);
    return `${num} ${maybePlural}`;
}

const formatDuration = (interval, unitFilter) => {
    const duration = interval.toDuration(unitFilter).toObject();

    return unitFilter
        .filter(unit => duration[unit] != 0)
        .map(unit => formatUnit(unit, duration[unit]))
        .join(`, `);
}
```

Here is some examples using it with some gotcha's to be mindful of:

```JS
const start = DateTime.fromISO('2019-01');
const end = DateTime.fromISO('2020-07');
const interval = start.until(end);
const unitFilter = ['years', 'months'];

// {years: 1 , months: 6} => "1 year, 6 months"
console.log( 'Duration is ' + formatDuration(interval, unitFilter) );

const dates = (x,y) => DateTime.fromISO(x).until(DateTime.fromISO(y));

// {years: 1 , months: 0} => "1 year"
console.log( 'Duration is ' + formatDuration(dates('2019-01', '2020-01'), unitFilter) );

// {years: 0,  months: 6} => "6 months"
console.log( 'Duration is ' + formatDuration(dates('2019-01', '2019-07'), unitFilter) );


const granular_example = dates('2020-01-01T21:07:03.000Z', '2020-02');
// Note, without a full ISO 8601 datetime string, no timezone designation is recognized,
// thus defaults to local timezone.
// DateTime.fromISO('2020-02').zoneName "Pacific/Auckland" in my case

// Note rounding not implemented
// { years: 0, months: 0, days: 29.5784375 } => "29.5784375 days"
console.log( 'Duration is ' + formatDuration(
    granular_example,
    ['years', 'months', 'days']
));

// { days: 29, hours: 13, minutes: 52, seconds: 57 } => "29 days, 13 hours, 52 minutes, 57 seconds"
console.log( 'Duration is ' + formatDuration(
    granular_example,
    ['days', 'hours', 'minutes', 'seconds']
));

// { hours: 7, minutes: 32, seconds: 57 } => "7 hours, 32 minutes, 57 seconds"
const hms_example = dates('09:27:03.000Z', '17:00Z');
console.log( 'Duration is ' + formatDuration(
    hms_example,
    ['hours', 'minutes', 'seconds']
));
```

**Comment by danielo515** [comment]
What are you using the imported luxon method for @polarathene ?

**Comment by polarathene** [comment]
@danielo515 it's used in the example code for `DateTime`, which creates the `luxon` intervals and duration objects. AFAIK, `date-fns` has an empty `Duration` section on their API docs, and that's important to use the solution. If you can format an object that has the units of the duration you want to format to a string like shown in the commented examples above, it should work with `date-fns` too, just replace the `duration` variable with that object.

**Comment by kopax** [comment]
Can I convert a date time in a readable human format using date-fns (and not duration) ?

**Comment by ikhnaton** [comment]
If anyone is still looking for a solution to this, how about this:

```
import intervalToDuration from "date-fns/intervalToDuration";

const dtest = (val, text, arr, required) =>
{
	if ((val > 0) || (required === true))
	{
		arr.push(`${val} ${text}${val === 1 ? "" : "s"}`);
		return true;
	}

	return false;
};

export const durationText = ({ start, end }) =>
{
	const duration = intervalToDuration({
		start,
		end
	});

	const response = [];
	let required = false;

	required = dtest(duration.years, "years", response, required);
	required = dtest(duration.months, "month", response, required);
	required = dtest(duration.days, "day", response, required);
	required = dtest(duration.hours, "hour", response, required);
	required = dtest(duration.minutes, "minute", response, required);
	dtest(duration.seconds, "second", response, true);

	return response.join(" ");
};
```

**Comment by YuraOvcharov** [comment]
```
import {  intervalToDuration, formatDuration } from 'date-fns'

export const customFormatDuration = ({ start, end }: { start: number, end: number }) => {
    const durations = intervalToDuration({ start, end })
    return formatDuration(durations)
}

customFormatDuration({ start: 0, end: 10800 * 1000}) // 3 hours
customFormatDuration({ start: 0, end: 108000 * 1000}) // 1 day 6 hours
```

**Comment by IonelLupu** [comment]
Thank you @YuraOvcharov . You saved my life :))

**Comment by mlarcher** [comment]
thank you @YuraOvcharov !
Anyone familiar with the lib would know if there is an easy way to localize the output ?

**Comment by 0xdevalias** [comment]
In case it helps others, `intervalToDuration` that is used in https://github.com/date-fns/date-fns/issues/229#issuecomment-646124041 appears to have been added in `v2.13.0`:

- https://date-fns.org/v2.13.0/docs/intervalToDuration

**Comment by latanoel** [comment]
@YuraOvcharov You're a life saver. Thank you
