### ISSUE TITLE
parse function throws TS error if using with one argument

### ISSUE THREAD

**Issue by Oleksii14** [date-fns/date-fns#2497]
```
const dateString = "Thu Jun 03 2021"
const value = parse(dateString) // TS Error

// (parameter) dateString: string
// Expected 3-4 arguments, but got 1.ts(2554)
// typings.d.ts(897, 5): An argument for 'formatString' was not provided.
```

To temporary ignore it, I need to use 

```
// eslint-disable-next-line
// @ts-ignore
```

Can you take a look?

**Comment by fturmel** [comment]
I believe this is the expected behavior for v2, as documented here: https://date-fns.org/docs/parse

If you are migrating from v1, there is a dedicated page in the docs as well that might help: https://date-fns.org/docs/Upgrade-Guide

The example you provided matches the native Date object's `toDateString` format, so I think it's safe to simply use the Date constructor to parse that string. `new Date('Thu Jun 03 2021')`

To use `date-fns` `parse`, this format string should work: `parse('Thu Jun 03 2021', 'EEE MMM dd yyyy', new Date())`

**Comment by Oleksii14** [comment]
@fturmel `parseISO` worked in my case 👍
