### ISSUE TITLE
Using the number 1 instead of the word "ein" for formatDuration in German locale

### ISSUE THREAD

**Issue by thexpand** [date-fns/date-fns#2505]
Hello. I tried using `formatDuration` to calculate a duration based on an interval. When I try it without a locale (i.e. in English) the result that I get is e.g. "1 year 1 month 15 days". However, when I add the German locale and try to format the same interval, I get "ein Jahr ein Monat 15 Tage". I am not a native German speaker, but it's strange that it does it only to number 1. It doesn't happen to other numbers, e.g. "2". Is there a reason why this is the behavior or is it a bug?

EDIT: My current workaround is to do a replace `formattedString.replace(/ein/g, '1')`

**Comment by kossnocorp** [comment]
As I can see in CLDR, using numbers is the correct way. @date-fns/i18n-de could you please chime in?

**Comment by saithis** [comment]
Embedded into a longer text up to and including 12, it should be written as eins, zwei, ... zwölf. Alone standing i think 1 is correct (or at least thats how most people do it). But from my observation many (mostly younger) people always use "1" instead of "ein" , even in a longer text.

If you don't know where it will he used and have to decide one way or the other, I think "1" is better than "ein", even though it will trigger some grammar nazis.

**Comment by janziemba** [comment]
I have created a PR. Does it make sense? https://github.com/date-fns/date-fns/pull/2575

**Comment by pex** [comment]
@saithis is right afaik - there is not an official rule two write 1-12 as a word.
On the other hand there is something special about the number 1: it is the only number that is pronounced and written differently when used with a subject.

```
1   | Eins    | Eine Minute
2   | Zwei    | Zwei Minuten
50  | Fünfzig | Fünfzig Minuten

1   | Eins    | Ein Monat
2   | Zwei    | Zwei Monate
50  | Fünfzig | Fünfzig Monate
```

This may be the reason why the number 1 is currently an exception.
Personally I must say having this exception *feels* more natural. "Eins Minute" is just wrong.

**Comment by Havock94** [comment]
Hello, I just noticed Italian locale has the same "issue" if we can call it like that, it uses the string "un" when the unit is 1, the number otherwise.

I see the PR for the German locale has been accepted, should we use it as a rule to always use numbers for durations? In that case I'd open a PR for the Italian locale.
Thanks
