### ISSUE TITLE
Format() converts 2ms to 30:00 in a different time zone

### ISSUE THREAD

**Issue by sunychibo** [date-fns/date-fns#2564]
Hi I'm not sure if this is a bug, maybe I missed something in the Time zone settings. I hope for your support.
I am using the library to implement time counters to calculate the time user is online.
To initialize the counter I need to convert the value in milliseconds from 
differenceInMilliseconds(new Date(), time) into the 'mm:ss' format 

And in my time zone on my PC (UTC+03:00):
format(2, 'mm:ss') returns 00:00

But on PC with (UTC+05:30):
format(2, 'mm:ss') returns 30:00

![image](https://user-images.githubusercontent.com/46617637/127140996-df0bb966-eedf-463c-821c-7e8c1cbd40db.png)

**Comment by fturmel** [comment]
It's a pretty weird hack to use `format` like this, and definitely not the right approach. It expects a Date object or ms since unix epoch as its first argument and is meant to work with dates, not intervals. That millisecond value will be converted to a Date object and local time zones will then come into play as you observed.

Have a look at `intervalToDuration`, it will help you extract the hours, minutes and seconds between two dates. From there, you can build your formatted string manually. https://date-fns.org/docs/intervalToDuration

```js
import { intervalToDuration } from "date-fns";

const start = new Date(2021, 0, 1, 14, 30, 11);
const end = new Date(2021, 0, 1, 16, 45, 28);

const duration = intervalToDuration({end, start});
console.log(duration); // { years: 0, months: 0, days: 0, hours: 2, minutes: 15, seconds: 17 }
```

They won't match the exact string format you were going for, but you should also consider the following functions for your use case:

https://date-fns.org/docs/formatDistanceToNowStrict (and other `formatDistance` variants)
https://date-fns.org/docs/formatDuration
https://date-fns.org/docs/formatRelative

Hope that was helpful!

**Comment by fturmel** [comment]
And to break down why `format` behaves that way in your example:

- `format(2, 'mm:ss')` is equivalent to `format(new Date(2), 'mm:ss')`
- `new Date(2)` is 2 milliseconds after Unix epoch, or `1970-01-01T00:00:00.002Z`
- `format` internally uses local time zones, _not_ UTC. If we execute the following script in `TZ=Asia/Calcutta` which is GMT+5:30, you can see that the values are based on that time zone.

```js
import { format } from 'date-fns'

const ms = 4000
const date = new Date(ms)

console.log(date.toISOString()) // 1970-01-01T00:00:04.000Z
console.log(date.toString())    // Thu Jan 01 1970 05:30:04 GMT+0530 (India Standard Time)

console.log(format(date, 'hh:mm:ss')) // 05:30:04
console.log(format(ms, 'hh:mm:ss'))   // 05:30:04

```

**Comment by fturmel** [comment]
Going to close this issue if you don't mind. Please comment if you are still having problems, and we can re-open it / continue to discuss.
