### ISSUE TITLE
`eachMinuteOfInterval` gives minutes outside of a given interval in some cases.

### ISSUE THREAD

**Issue by nodeadtree** [date-fns/date-fns#2605]
The `eachMinuteOfInterval` function will return a minute that is not within the given interval if the start date on the interval has non-zero seconds or milliseconds.

Simple test case.
```js
const assert = require('assert');
const { eachMinuteOfInterval, isWithinInterval } = require('date-fns');

const start = new Date(2020, 8, 20, 10, 10, 30);
const end = new Date(2020, 8, 20, 10, 11, 30);
const interval = { start, end };
const minutes = eachMinuteOfInterval(interval);
assert(minutes.every(x => isWithinInterval(x, interval))); // Should pass, but it does not.
```

**Comment by geeksilva97** [comment]
I think that is the expected behavior. If you debug the `minutes` variable you'll see the array items:

```js
console.log(JSON.stringify(minutes)); // Prints: ["2020-09-20T13:10:00.000Z","2020-09-20T13:11:00.000Z"]
```

`eachMinuteOfInterval` correctly returns the minutes of the interval, but note that the minutes are at the beginning (with the seconds set to zero) so checking with `isWithinInterval` is not working. The interval provided for isWithinInterval has seconds.

So, the first item of `minutes` array (`2020-09-20T13:10:00.000Z`) is correctly not in the interval of `2020-09-20T13:10:30.000Z` and `2020-09-20T13:11:30.000Z`. This item is thirty seconds before the interval starts.

To confirm, check this same example using `startOfMinute` in the range:

```ts
const assert = require('assert');
const { eachMinuteOfInterval, isWithinInterval, startOfMinute } = require('date-fns');

const start = new Date(2020, 8, 20, 10, 10, 30);
const end = new Date(2020, 8, 20, 10, 11, 30);
const interval = { start: startOfMinute( start ), end: startOfMinute( end ) };
const minutes = eachMinuteOfInterval(interval);

assert(minutes.every(x => isWithinInterval(x, interval))); // It will pass
```

**Comment by nodeadtree** [comment]
That makes sense.

Did I miss something detailing this as expected behavior in the documentation? Am I just generally oblivious wrt time and its nomenclature? Either way, thanks for the clarification!
