### ISSUE TITLE
[License Help] About License

### ISSUE THREAD

**Issue by morningman** [date-fns/date-fns#2624]
Dear date-fns team:

I'm using the [ant-design](https://github.com/ant-design/ant-design) in my project.
And the `ant-design` uses `date-fns`.

I notice the `date-fns` is under MIT license, and one of its dependency `cloc` is under GPL license, which is not compatible with MIT.

Is there a way to solve the licensing problem?

[1] https://github.com/date-fns/date-fns/blob/5cffe310080b7fc7954fe7f4584e016737ca39e1/package.json#L69

Related: #190

**Comment by fturmel** [comment]
`date-fns` has no production dependencies. I don't think the licenses of third party libraries defined in `devDependencies` should matter since they won't be installed in your project and are not distributed.

<img width="367" alt="Screen Shot 2021-09-12 at 10 21 01 PM" src="https://user-images.githubusercontent.com/4009209/133014498-1cb8d191-04c2-46e1-82ce-561f5c2fd80c.png">
