### ISSUE TITLE
isPast does not document the allowable "number" parameter as unix timestamp in milliseconds.

### ISSUE THREAD

**Issue by landonbuttars** [date-fns/date-fns#2633]
date-fns version: 2.23.0

The isPast function treats unix timestamps differently than dates. 

It is causing incorrect results when passing a unix timestamp to the function. 
In my limited testing, it returns the correct result for past unix dates but incorrect results for future unix dates.

Simple workaround for now is to use the fromUnixTimestamp function but this isn't optimal.

If this is intended functionality, it should be more clearly documented.

Here is a bare bones example: https://codesandbox.io/s/date-fns-v2-forked-ru0vb?file=/src/index.js

**Comment by fturmel** [comment]
JS Date's timestamps are _milliseconds_ since unix epoch, not seconds.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps

```js
new Date(2546886290) // Fri Jan 30 1970 06:28:06 GMT-0500 (Eastern Standard Time)
new Date(969049490) // Mon Jan 12 1970 00:10:49 GMT-0500 (Eastern Standard Time)

new Date(2546886290 * 1000) // Thu Sep 15 2050 16:24:50 GMT-0400 (Eastern Daylight Time)
new Date(969049490 * 1000) // Fri Sep 15 2000 16:24:50 GMT-0400 (Eastern Daylight Time)
```

**Comment by landonbuttars** [comment]
@fturmel makes sense. Ty.

Since isPast takes a number as a parameter I think it would be useful to have it documented that it expects an epoch time in milliseconds as the param.

**Comment by fturmel** [comment]
@landonbuttars Almost every 200+ functions in `date-fns` takes a `Date | number` argument, where `number` is the timestamp in ms since epoch (what the JS Date constructor accepts). I think it's assumed in the JS ecosystem that timestamps are in milliseconds and not in seconds.

I can understand that it might be confusing coming from another language that has a different convention, but this doesn't just affect `isPast` in this library.

I proposed not too long ago to clarify the `fromUnixTime` jsdocs that the argument was in _seconds_ exactly because the assumed default would be in milliseconds. #2523

I'm not against clarifying the docs, but if we think `isPast` should be clarified, it should apply to just about every single function in the library or there should be a blanket statement somewhere.

**Comment by landonbuttars** [comment]
@fturmel I agree with the change. I think there should be an example for each valid input type. This seems larger than just a few of the functions. Closing in favor for a larger issue.
