### ISSUE TITLE
How to parse a date string as a specific time zone

### ISSUE THREAD

**Issue by hardysabs2** [date-fns/date-fns#2642]
I cannot quite find the right function to build a UTC date object from a date string, the format of the date string and the TZ Database name that the date in the date string is in.

**Comment by ryanb** [comment]
@hardysabs2 you need to use functions in `date-fns-tz` to convert to and from the timezone. Something like this.

```js
import utcToZonedTime from "date-fns-tz/utcToZonedTime";
import zonedTimeToUtc from "date-fns-tz/zonedTimeToUtc";
import parse from "date-fns/parse";

parseWithTimeZone(dateStr, formatStr, referenceDate, timeZone) {
  const zonedDate = utcToZonedTime(referenceDate, timeZone);
  const parsedDate = parse(dateStr, formatStr, zonedDate);
  return zonedTimeToUtc(parsedDate, timeZone);
}
```

Does that work for you?

**Comment by asennikov** [comment]
it doesn't work if your `dateStr` and `formatStr` already include the offset explicitly, e.g.:
```
parseWithTimeZone("2021-01-02T00:00:00Z", "yyyy-MM-dd'T'HH:mm:ssXXX", new Date(), "UTC");
```
returns `2021-01-02T03:00:00.000Z` (my local TZ offset is UTC+3, so it added it in there)

another example with preset TZ:
```
parseWithTimeZone("2021-01-02T00:00:00-07:00", "yyyy-MM-dd'T'HH:mm:ssXXX", new Date(), "UTC");
```
returns `2021-01-02T10:00:00.000Z`, the expected value would be 3 hours earlier in UTC (matches my local offset).

**Comment by tur-nr** [comment]
Not sure if we are trying to achieve the same thing but for me I had a date string without the timezone information. Every time I tried to parse it as a date it would give me a date in the machines local timezone. I just forced the zone of the string using `zonedTimeToUtc` from `date-fns-tz`.

```js
const { zonedTimeToUtc } = require("date-fns-tz");

const string = "December 31 1999 23:59:59"; // date string WITHOUT zone information
const date = new Date(string); // parse the string to a date

// the machine will apply current system zone to the parsed date,
// let's assume the machine is in "Australia/Sydney"
console.log({ time: date.getTime(), locale: date.toLocaleString());
// => "{ time: 946645199000, locale: '31/12/1999, 11:59:59 pm' }"

const zone = "Europe/Berlin"; // let's assume the date string zone
const utc = zonedTimeToUtc(date, zone); // convert to utc forcing the zone

// now we have a date that is zoned "Australia/Sydney" because of the machine
// however it holds the parsed date string from "Europe/Berlin"
console.log({ time: date.getTime(), locale: date.toLocaleString());
// => "{ time: 946681199000, locale: '01/01/2000, 9:59:59 am' }"
```

If this is not what you were trying to achieve, I'm gonna leave this here for myself to learn how to do this again next year 😅

**Comment by rnfbr1** [comment]
Hi , i have this date that i have to parse and calculate the local timezone for.  The date looks like this:   03/20/2024 01:30:00 PM EDT .  I always get an **invalid date** error.

This is how i am attempting to parse the date shown above: 

`const parsedDate = parse(dateString, 'MM/dd/yyyy hh:mm:ss a sss', new Date());`

I always get the invalid date error.  but if i do it like this 

`const parsedDate = new Date(dateString);`

it does not give me any errors  but it does not parse the timezone, only the date and time

My use case is about transforming the date in this format : MM/dd/yyyy hh:mm:ss a zzz  to time to another timezone  in this same very format. 

This is my entire code:  

`export const transformTimezoneFromDateString = (dateString, timezone = 'UTC') => {
  try {
    // Parse the input date string
    const parsedDate = parse(dateString, 'MM/dd/yyyy hh:mm:ss a sss', new Date());

    //const parsedDate = new Date(dateString);

    // Convert to the specified timezone
    const formattedDate = zonedTimeToUtc(parsedDate, timezone);

    // Format the output date string
    const outputFormat = 'MM/dd/yyyy hh:mm:ss a sss';
    const transformedDate = format(formattedDate, outputFormat, { timeZone: timezone });

    return transformedDate;
  } catch (error) {
    console.error('Error transforming date:', error);

    return null; // Return null or handle the error as needed
  }
};`

**Comment by fturmel** [comment]
@rnfbr1 this is the wrong place to get support for [date-fns-tz](https://github.com/marnusw/date-fns-tz), you should probably ask there.

Couple things quickly though:
- the `sss` token doesn't exist in date-fns
- the `zzz` token is only available in date-fns-tz `format`, it can't be used with date-fns `parse`. Consult the [docs](https://date-fns.org/docs/parse).
- "EDT" is probably not a valid timezone input here, I believe you would need to pass either UTC/Z, the timezone offset, or the location based [IANA TZ identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) (ex: America/New_York instead of EDT/EST). These non-location based abbreviations are more limited and can be ambiguous (CST can mean Central Standard Time or China Standard Time).

As for the rest of this issue/thread, it seemed somewhat resolved? LMK if I misunderstood and we can re-open. Again it's probably best to ask for support in the date-fns-tz project though. There is a [UTC Date extension library](https://github.com/date-fns/utc) that can be used with date-fns v3, but still no timezone-specific manipulations without date-fns-tz being involved.

**Comment by rnfbr1** [comment]
Thank you @fturmel , that was pretty helpful and helped me solve my problem. Using IANA TZ identifier and the zzz representation instead of sss did the trick.  Best regards
