### ISSUE TITLE
isValid(new Date('2021-11-45'))

### ISSUE THREAD

**Issue by GaylordP** [date-fns/date-fns#2806]
Hello,

Sorry for my bad english, i'm french.

I would like to check the validity of a date. However, when I test the validity "2021-11-45" it returns true.

    isValid(new Date('2021-11-45')) // return true

I think date-fns returns true without really checking if the date exists, just if the format is correct. Can you help me ?

Thanks in advance

**Comment by fturmel** [comment]
I can't reproduce the issue on my end with your example. Can you confirm which browser / JavaScript runtime and `date-fns` version you're using?

```js
import { isValid } from "date-fns";

const date = new Date("2021-11-45");
const res = isValid(date);

console.log(date.getTime()); // NaN
console.log(res); // false
```

**Comment by GaylordP** [comment]
Thanks for your reply :)

I have this result : 

    const testDate = new Date("2021-11-45");
    const res = isValid(testDate);

    console.log(testDate.getTime()); // 1639526400000
    console.log(res); // true

I use `date-fns ^2.27.0` with `react-native ^0.66.3`

**Comment by leshakoss** [comment]
Hi @GaylordP!

`Date` object is essentially a wrapper over a single value - the date's timestamp which is a number. What `isValid` does is it checks whether that value is `NaN` or not. `isValid` can't access the string `'2021-11-45'` because once you put it inside `new Date` constructor, it is gone.

The function you're looking for is [`isMatch`](https://date-fns.org/v2.27.0/docs/isMatch):
```js
isMatch('2021-11-45', 'yyyy-MM-dd') //=> false
isMatch('2021-11-31', 'yyyy-MM-dd') //=> false
isMatch('2021-11-30', 'yyyy-MM-dd') //=> true
```

**Comment by GaylordP** [comment]
Thanks very much :)
