### ISSUE TITLE
isSameMonth returning false for 31 of may 22

### ISSUE THREAD

**Issue by enkopvand** [date-fns/date-fns#3034]
Hello,

Can anyone explain to me why this results in true + false:

```
let stringDate1 = new Date('2022-05-30T22:00:00.000Z');
let stringDate2 = new Date('2022-05-31T22:00:00.000Z');
let stringDate3 = new Date('2022-05-27T22:00:00.000Z');
console.log(dateFns.isSameMonth(stringDate1, stringDate3));
console.log(dateFns.isSameMonth(stringDate2, stringDate3));
true
false
```

**Comment by rbrtmrln** [comment]
this is dependent of the local timezone, since date3 is the first of june in gmt +2 (when you switch your OS to a different timezone with less offset this returns true correctly)
see line: https://github.com/date-fns/date-fns/blob/master/src/isSameMonth/index.ts#L37
i'm not sure however what is more correct, from utc point of view these dates are the same month, from your local client pov these are different.
i think since this is a client library, the current behaviour is correct
