### ISSUE TITLE
roundToNearestMinutes roundingMethod producing unexpected results

### ISSUE THREAD

**Issue by im28** [date-fns/date-fns#3129]
When using `roundToNearestMinutes` function the rounding method doesn't seem to produce an expected result, or maybe there is something I'm missing.

For Example
`const result = roundToNearestMinutes(new Date(2022, 6, 24, 0, 28, 59), {
  nearestTo: 1,
  roundingMethod: "floor"
});
console.log(result);`

Produces
Sun Jul 24 2022 00:29:00 GMT+0800 (Singapore Standard Time)
Expected
Sun Jul 24 2022 00:28:00 GMT+0800 (Singapore Standard Time)

`const result = roundToNearestMinutes(new Date(2022, 6, 24, 0, 28, 59), {
  nearestTo: 1,
  roundingMethod: "ceil"
});
console.log(result);`

Produces
Sun Jul 24 2022 00:30:00 GMT+0800 (Singapore Standard Time)
Expected
Sun Jul 24 2022 00:29:00 GMT+0800 (Singapore Standard Time)

**Comment by DavidPCherry** [comment]
Having the same problem with roundToNearestMinutes function  producing the correct result.  

Example
const result = roundToNearestMinutes(new Date("01/01/1970 2:40:00"), { nearestTo: 15, roundingMethod: "ceil" }); 
console.log(result);

Produces
Thu Jan 01 1970 03:00:00 GMT-0600 (Central Standard Time)

Expected
Thu Jan 01 1970 02:45:00 GMT-0600 (Central Standard Time)


I am not familiar with the date-fns code base but it looks like the bug is in the following function:

function roundToNearestMinutes(dirtyDate, options) {
    var _options$nearestTo;

    if (arguments.length < 1) {
        throw new TypeError('1 argument required, but only none provided present');
    }

    var nearestTo = (0, _index3.default)((_options$nearestTo = options === null || options === void 0 ? void 0 : options.nearestTo) !== null && _options$nearestTo !== void 0 ? _options$nearestTo : 1);

    if (nearestTo < 1 || nearestTo > 30) {
        throw new RangeError('`options.nearestTo` must be between 1 and 30');
    }

    var date = (0, _index.default)(dirtyDate);
    var seconds = date.getSeconds(); // relevant if nearestTo is 1, which is the default case

    var minutes = date.getMinutes() + seconds / 60;
    var roundingMethod = (0, _index2.getRoundingMethod)(options === null || options === void 0 ? void 0 : options.roundingMethod);
    var roundedMinutes = roundingMethod(minutes / nearestTo) * nearestTo;
    var remainderMinutes = minutes % nearestTo;
    var addedMinutes = Math.round(remainderMinutes / nearestTo) * nearestTo;
    return new Date(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), roundedMinutes + addedMinutes);
}

Why are we rounding actual minutes and remainder minuets then adding them together.  I removed the "var remainderMinutes " line and the "var addedMinutes" line and changed the return line to return new Date(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), roundedMinutes );.  I walked a small set of use cases that affect my project and this seems to be a correct fix.

Here is the function after the changes: 

function roundToNearestMinutes(dirtyDate, options) {
    var _options$nearestTo;

    if (arguments.length < 1) {
        throw new TypeError('1 argument required, but only none provided present');
    }

    var nearestTo = (0, _index3.default)((_options$nearestTo = options === null || options === void 0 ? void 0 : options.nearestTo) !== null && _options$nearestTo !== void 0 ? _options$nearestTo : 1);

    if (nearestTo < 1 || nearestTo > 30) {
        throw new RangeError('`options.nearestTo` must be between 1 and 30');
    }

    var date = (0, _index.default)(dirtyDate);
    var seconds = date.getSeconds(); // relevant if nearestTo is 1, which is the default case

    var minutes = date.getMinutes() + seconds / 60;
    var roundingMethod = (0, _index2.getRoundingMethod)(options === null || options === void 0 ? void 0 : options.roundingMethod);
    var roundedMinutes = roundingMethod(minutes / nearestTo) * nearestTo;
    return new Date(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), roundedMinutes);
}

Hope this helps
