### ISSUE TITLE
Methods for working with time durations

### ISSUE THREAD

**Issue by calvintennant** [date-fns/date-fns#3228]
Happy to see methods like `eachDayOfInterval`, `eachWeekOfInterval`, etc. The method `intervalToDuration` is also very nice. 

When working with `eachDayOfInterval` I ran into a catch where the start and end dates in my dataset are at midnight. I can see how technically both days belong to the interval, although zero seconds of the last day are part of the interval. It would be nice to have trailing edge option to account for this case 🤔 

My workaround is to create a duration object for each day of interval and use this to determine if any seconds of this day are part of the interval. If the duration ranging from `startOfDay` to the end of my interval is 0 seconds, than I can exclude this trailing edge. 

I was surprised to see that there is no easy way with date-fns to get the total number of seconds belonging to an interval. I suppose I can `getTime` on the dates, divide the result by 1000 and subtract the end from the start, but I was hoping to leave this kinda logic to the library so my code remains legible. I found another package to solve my use-case: https://www.npmjs.com/package/iso8601-duration. It would be nice to have `intervalToSeconds`, `intervalToMinutes`, etc as methods available in `date-fns` library (these methods would be returning a number, not an array of dates)

If the maintainers of this project think that it is a useful feature that no one else is working on, I might try my hand at a contribution in the future. Please let me know. If not, feel free to close the issue :)

**Comment by IgnusG** [comment]
I think there already is https://date-fns.org/v2.29.3/docs/differenceInSeconds to get the difference of 2 dates (which an interval consists of - `differenceInSeconds(interval.start, interval.end)`). But there isn't a method to get the total number of seconds from an existing duration object.

Because you however loose information about the dates (you only now the difference but not start and end) you cannot calculate eg. the total number of seconds just from a duration since some years for example might have more seconds than others (leap years). So you cannot just do `duration.years * 365 * 24 * 60 * 60`.

**Comment by calvintennant** [comment]
Thanks for getting back to me @IgnusG. The method `differenceInSeconds` is what I was looking for. Will close, thanks again.

PS: Related to the second paragraph in your response, iso8601-duration package offers an optional date property as a baseline that defaults to the current date.
