### ISSUE TITLE
getWeek not working well

### ISSUE THREAD

**Issue by adj87** [date-fns/date-fns#3373]
I just noticed that getWeek not working well
2nd january is first week of january and not second.
Here is the example
I am not sure if is the function or spanish locale.
[(https://codesandbox.io/s/date-fns-v2-forked-hqihjb?file=/src/index.js:0-172)]

**Comment by AlbertoOkra** [comment]
[](https://codesandbox.io/s/date-fns-v2-forked-hqihjb?file=/src/index.js:0-172)

**Comment by morsko1** [comment]
As per my understanding, the week number for a given date can vary depending on the locale.
Each locale has its own options for determining the week number, such as `weekStartsOn` and `firstWeekContainsDate`.
For example, in the `es` (Spanish) locale, the week starts on Monday and the first week of the year is the one that contains January 1st.
Here is the config from `src/locale/es/index.ts`
```
const locale: Locale = {
  code: 'es',
  formatDistance: formatDistance,
  formatLong: formatLong,
  formatRelative: formatRelative,
  localize: localize,
  match: match,
  options: {
    weekStartsOn: 1 /* Monday */,
    firstWeekContainsDate: 1,
  },
}
```

According to these options, January 1, 2023 (which is a Sunday) belongs to the week December 26, 2022 (Monday) - January 1, 2023 (Sunday), which is considered as week number 1 since it contains the `firstWeekContainsDate` set to 1.
Similarly, January 2, 2023 (which is a Monday) belongs to the next week, which is considered as week number 2 in the `es` locale.

If you want to calculate the week number based on the ISO-8601 standard, you can use the getISOWeek method.
According to the ISO-8601 standard, the week containing the first Thursday of the year is considered as week number 1.
For instance, in the case of January 2, 2023, the week containing the first Thursday of the year (which is January 5, 2023) is the same as the week that contains January 2, 2023.
Therefore, January 2, 2023 would be considered as part of week number 1 according to the ISO-8601 standard.

Would be glad if someone can clarify that.
