### ISSUE TITLE
endOfDay is not calculating correctly the date

### ISSUE THREAD

**Issue by MaxOrelus** [date-fns/date-fns#3410]
This method is buggy. If you have a time value closer to the middle of the day or more -- it works correctly. If you have a date value that you convert into a Date object, all bets are off.

```js
let dateString = '2023-05-03'

let dateObject = new Date(dateString).toISOString() // 2023-05-03T00:00:00.000Z

let endOfDayDate = endOfDay(dateObject).toISOString() // 2023-05-03T03:59:59.999Z
```

What it should do is bump the date `2023-05-04T03:59:59.999Z`

**Comment by foolmarshal** [comment]
Hi @MaxOrelus ,

Isn't this the expected behaviour.

As per official documentation [https://date-fns.org/v2.30.0/docs/endOfDay#examples](https://date-fns.org/v2.30.0/docs/endOfDay#examples), `endOfDay` should return the dateTime for end of current day, i.e. `2023-05-03T23:59:59.999Z` (for your example).

Also, the resulting date object from `endOfDay` is according to user's `local` timezone and not `UTC`.

Also, as you mentioned that after middle of the day, the result of `endOfDay` bumps to next day, that'll because the dateTime string you passed will be considered in `UTC` timezone (+00:00) and final dateObject is adjusted according to your `local` timezone.

**Comment by MaxOrelus** [comment]
Okay, if that's the intended functionality, then I'll leave it be. Thanks
