### ISSUE TITLE
intervalToDuration - wrong days calculation

### ISSUE THREAD

**Issue by it20217** [date-fns/date-fns#3461]
intervalToDuration method provides wrong days calculation:

const days = intervalToDuration({
    start: new Date("2023-05-20"),
    end: new Date("2023-06-24")
  }).days;

output is 4. should be 35

the bug is generated here -> https://codesandbox.io/s/days-calculator-1woj9?file=/src/App.js:127-240

**Comment by maximtop** [comment]
for these dates `intervalToDuration` correctly returns a Duration object

```javascript
{
  years: 0,
  months: 1,
  days: 4,
  hours: 0,
  minutes: 0,
  seconds: 0
}
 ```
 
The output is 1 month and 4 days because the interval between "2023-05-20" and "2023-06-24" includes the remainder of May (11 days), all of June (30 days), and the start of July (up to the 4th). So, while there are more than 4 days between those two dates, the intervalToDuration method breaks down the duration into its largest possible units first (i.e., months), then provides the remainder in the next largest units (i.e., days).

**Comment by it20217** [comment]
thanks for clarification. clear
