### ISSUE TITLE
parseISO not working properly with small years

### ISSUE THREAD

**Issue by killiangemoets** [date-fns/date-fns#3627]
When putting my location in London, I have the following:

```
import { parseISO } from "date-fns";

const date =  0202-01-25T00:00:00.000Z
const newDate = parseISO(date) // newDate = Sun Jan 24 0202 23:58:45 GMT-0001 (Greenwich Mean Time)

const date2 =  2022-01-25T00:00:00.000Z
const newDate2 = parseISO(date) // newDate2 =  Tue Jan 25 2022 00:00:00 GMT+0000 (Greenwich Mean Time)
```

It's very weird that for a very small year (202 here), I receive a date with a time offset of 1min45 from Greenwich.
However, for a year big enough (2022 here), I don't have any offset from Greenwich.

Any idea why?

**Comment by kossnocorp** [comment]
I can't remember from the top of my head the exact explanation, but since timezones is a relatively modern concept, computers still need to calculate time in the past. They use somewhat complicated calculations based on a proximate latitude.

If you're curious, I welcome you to find the explanation and share it here. If I were you, I would start with the ECMAScript standard. I think I saw it there.
