### ISSUE TITLE
`parseISO` function forced timezone state

### ISSUE THREAD

**Issue by Malix-off** [date-fns/date-fns#3648]
There is an issue with the [`parseISO` function](https://date-fns.org/v3.0.6/docs/parseISO)

## The problem

With GMT+ timezones, the date output is not a part of the given GMT iso string year/month/week/day
(i.e. `parseISO("2024-W01")` in a GMT+1 timezone outputs
`Mon Jan 01 2024 00:00:00 GMT+0100 (Central European Standard Time)` === `Sun Dec 31 2023 23:00:00 GMT`
instead of the often desired
`Mon Jan 01 2024 01:00:00 GMT+0100 (Central European Standard Time)` === `Mon Jan 01 2024 00:00:00 GMT`
)

### 🙁 Actual behavior

[`parseISO` function](https://date-fns.org/v3.0.6/docs/parseISO) must depends on timezone

### 🙂 Expected behavior

[`parseISO` function](https://date-fns.org/v3.0.6/docs/parseISO) isn't forced to depend on timezone

## Possible Solution

add a `timezone?: boolean` property to `ParseISOOptions`
	_**Note**: could, as a second proposal, also be used with a string value to change the timezone into which the iso string would be parsed_

## Debug information

- date-fns version: 3.0.6
- Browser/Node.js version: Chrome Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by Malix-off** [comment]
It might actually be desired?
In this way, what would be the most straightforward way to make it not take timezone into account?
Is it impossible and the [`parse` function](https://date-fns.org/v3.0.6/docs/parse) should be used instead?

**Comment by kossnocorp** [comment]
Do I understand correctly that you want to parse the date into UTC instead of the local timezone?

date-fns works consistently across all functions and always returns/works with dates in the local timezone unless the timezone is a part of the string. If you want to get UTC, you can use [`transpose`](https://date-fns.org/v3.0.6/docs/transpose) in combination with [`UTCDate`](https://github.com/date-fns/utc):

```ts
const date = parseISO("2024-W01");
//=> Sun Dec 31 2023 23:00:00 GMT

const utcDate = transpose(date, UTCDate);
//=> "Mon Jan 01 2024 00:00:00 GMT"
```

Adding this functionality to `parseISO` doesn't make sense as it will require extra dependencies and make the function bigger and less straightforward.

Another solution, if you control the string, is to explicitly specify the timezone (add `Z` for UTC):

```ts
parseISO("2024-W01").toString()
//=> 'Mon Jan 01 2024 00:00:00 GMT+0800 (Singapore Standard Time)'

parseISO("2024-W01Z")
//=> 'Mon Jan 01 2024 08:00:00 GMT+0800 (Singapore Standard Time)'
```

Closing as I don't see anything actionable from my side.
