### ISSUE TITLE
removing one day from on leap year.

### ISSUE THREAD

**Issue by Miguerfi** [date-fns/date-fns#3727]
when i'm testing my application i noticed something, on leap years the date-fns remove one day when use the format option.
input i'm using:`{
    "from": "2024-03-01T00:00:00.000000Z",
    "to": "2024-03-11T00:00:00.000000Z"
}`
  
the code to show the output:
```typescript

         {date && date.from ? (
              format(parseISO(date.from.toString()), "dd/MM/yyyy", {
                locale: ptBR,
              }) + " - "
            ) : (
              <span>Escolha uma data</span>
            )}
            {date && date.to
              ? format(parseISO(date.to.toString()), "dd/MM/yyyy", {
                  locale: ptBR,
                })
              : null}
```

and the output will be:
{
    "from": "2024-02-29T00:00:00.000000Z",
    "to": "2024-03-10T00:00:00.000000Z"
}

**Comment by fturmel** [comment]
Use [UTCDate](https://github.com/date-fns/utc) to stay in UTC throughout your operations. The shift you observed is probably happening because of local time zones.

```ts
import { UTCDate } from '@date-fns/utc';
import { format } from 'date-fns';

const from = new UTCDate('2024-03-01T00:00:00.000000Z');
const to = new UTCDate('2024-03-11T00:00:00.000000Z');

const pattern = 'dd/MM/yyyy';
const result = format(from, pattern) + ' - ' + format(to, pattern);

console.log(result); // 01/03/2024 - 11/03/2024
```

Also:
- No need to call `.toString()` on a string
- No need for `parseISO()` here since your input matches the [ecmascript date time standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format)
  - Note that while it doesn't break parsing, your input has microsecond precision (6 digits) while the native Date only goes to milliseconds (3 digits)
- Because your are only formatting numerical days/months/years, none of the locale-specific features come in play so you could leave that out too.

**Comment by Miguerfi** [comment]
I identified the issue... but thanks! The problem was that the time zone in Brazil was three hours behind, so when I sent the time with 00:00:00, the parsing to the Brazilian time zone subtracted three hours, causing it to go back one day.
