### ISSUE TITLE
Error TS2614: Module has no exported member

### ISSUE THREAD

**Issue by filipkis** [date-fns/date-fns#3747]
Hi there, 

We're on recent versions of `date-fns` (3.6.0) and `typescript` (5.4.3) and have all our date-fns use named imports yet we're still getting the Module has no exported member error. The worst thing is if we change 

```js
import { parseISO } from 'date-fns/parseISO';
```

to

```js
import parseISO from 'date-fns/parseISO';
```

Then the TS error goes away. Now, I've seen conversations like #3635 where it points to possible issues with CRA or Next.JS, but we don't use any of these (see our package.json at the end). 

So I'd appreciate any help in figuring out where the problem lies and how to resolve it. Or should we just use the default imports?

Part of our tsconfig

```json
{
  "compilerOptions": {
    "declaration": false,
    "lib": ["es6", "dom"],
    "module": "ES2020",
    "moduleResolution": "Bundler",
    "sourceMap": true,
    "target": "es6",
    "jsx": "react-jsx",
    "noEmit": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "checkJs": true,
    "allowSyntheticDefaultImports": true,
    "plugins": [],
    "strict": true,
    "noImplicitReturns": true,
    "resolveJsonModule": true
  },
  ```
  
 And our package.json
```json
"dependencies": {
    "@activeadmin/activeadmin": "^3.2.0",
    "@formatjs/intl-pluralrules": "^5.2.12",
    "@formatjs/intl-relativetimeformat": "^11.2.12",
    "@fortawesome/fontawesome-free": "^6.5.1",
    "@popperjs/core": "^2.11.7",
    "@rails/ujs": "^7.1.3",
    "@sentry/browser": "7.108.0",
    "@sentry/integrations": "7.108.0",
    "@storybook/addon-styling": "^1.3.7",
    "@tanstack/react-table": "^8.15.0",
    "@typeform/embed-react": "^3.16.0",
    "activeadmin_addons": "^1.0.0",
    "autosize": "^6.0.1",
    "axios": "^1.6.8",
    "axios-retry": "^4.1.0",
    "big.js": "^6.2.1",
    "bootstrap": "^5.3.3",
    "braintree-web": "^3.101.0",
    "braintree-web-drop-in": "^1.42.0",
    "classnames": "^2.5.1",
    "core-js": "3",
    "date-fns": "3.6.0",
    "date-fns-tz": "^2.0.0",
    "esbuild-loader": "^4.1.0",
    "intl": "^1.2.5",
    "isomorphic-dompurify": "2.6.0",
    "jquery": "^3.7.1",
    "jquery-ui-bundle": "^1.12.1-migrate",
    "jsoneditor": "^10.0.2",
    "jsvat": "^2.5.3",
    "load-script": "^2.0.0",
    "localsync": "^1.7.2",
    "lodash": "^4.17.21",
    "marked": "^12.0.1",
    "medium-editor": "^5.23.2",
    "mobx": "^6.12.1",
    "mobx-react-lite": "^4.0.6",
    "mobx-state-tree": "^5.4.1",
    "prop-types": "^15.7.1",
    "pusher-js": "^8.3.0",
    "query-string": "^7.1.3",
    "rails-erb-loader": "^5.5.1",
    "raven-js": "^3.18.1",
    "react": "^18.2.0",
    "react-bootstrap": "^2.10.2",
    "react-bootstrap-typeahead": "^6.3.2",
    "react-color": "^2.19.3",
    "react-datepicker": "^4.25.0",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-intl": "^5.24.0",
    "react-on-rails": "13.4.0",
    "react-responsive": "^10.0.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.3.4",
    "react-router-dom-v5-compat": "^6.22.3",
    "react-swipeable": "^7.0.1",
    "resize-observer-polyfill": "^1.5.1",
    "resolve-url-loader": "^5.0.0",
    "select2": "^4.0.13",
    "sortablejs": "1.15.2",
    "thenby": "^1.3.4",
    "tinycolor2": "^1.6.0",
    "vm-browserify": "^1.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.24.3",
    "@babel/plugin-proposal-export-default-from": "^7.24.1",
    "@babel/plugin-transform-runtime": "7.24.3",
    "@babel/preset-env": "7.24.3",
    "@babel/preset-react": "^7.24.1",
    "@babel/preset-typescript": "^7.24.1",
    "@babel/runtime": "7.24.1",
    "@size-limit/preset-app": "^8.2.4",
    "@storybook/addon-actions": "^7.6.16",
    "@storybook/addon-essentials": "^7.6.16",
    "@storybook/addon-interactions": "^7.6.16",
    "@storybook/addon-links": "^7.6.16",
    "@storybook/addons": "^7.6.16",
    "@storybook/blocks": "^7.6.16",
    "@storybook/components": "^7.6.16",
    "@storybook/manager-api": "^7.6.16",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/react": "^7.6.16",
    "@storybook/react-webpack5": "^7.6.16",
    "@storybook/testing-library": "^0.2.2",
    "@storybook/theming": "7.6.16",
    "@stylistic/eslint-plugin": "^1.7.0",
    "@testing-library/dom": "^9.3.4",
    "@testing-library/jest-dom": "^6.4.2",
    "@testing-library/react": "^14.2.2",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^14.5.2",
    "@types/autosize": "^4.0.3",
    "@types/big.js": "^6.2.2",
    "@types/braintree-web": "^3.96.11",
    "@types/braintree-web-drop-in": "^1.39.3",
    "@types/grecaptcha": "^3.0.9",
    "@types/jest": "^29.5.12",
    "@types/react-datepicker": "^4.19.5",
    "@types/react-helmet": "^6.1.11",
    "@types/react-router": "^5.1.20",
    "@types/react-router-dom": "^5.3.3",
    "@types/sortablejs": "^1.15.8",
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    "@vitejs/plugin-react-swc": "^3.6.0",
    "@webpack-cli/serve": "2.0.5",
    "@zxing/text-encoding": "^0.9.0",
    "auto-changelog": "^2.4.0",
    "axios-mock-adapter": "^1.22.0",
    "babel-loader": "^9.1.3",
    "babel-plugin-dynamic-import-node": "^2.3.3",
    "babel-plugin-macros": "^3.1.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "compression-webpack-plugin": "11",
    "css-loader": "^6.10.0",
    "css-minimizer-webpack-plugin": "^6.0.0",
    "dotenv": "^16.4.5",
    "esbuild": "^0.20.2",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jest": "^27.9.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-storybook": "^0.8.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "jest-junit": "^16.0.0",
    "js-yaml": "^4.1.0",
    "mini-css-extract-plugin": "^2.8.1",
    "mutationobserver-shim": "^0.3.7",
    "node-libs-browser": "^2.2.1",
    "postcss": "^8.4.38",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^16.1.0",
    "postcss-loader": "^8.1.1",
    "postcss-preset-env": "9.5.2",
    "prettier": "^3.2.5",
    "pretty-quick": "^4.0.0",
    "pusher-js-mock": "^0.2.1",
    "qrcode.react": "^3.1.0",
    "react-refresh": "^0.14.0",
    "sass-embedded": "^1.72.0",
    "sass-loader": "^14.1.1",
    "script-loader": "^0.7.2",
    "shakapacker": "7.2.3",
    "size-limit": "^8.2.4",
    "storybook": "^7.6.16",
    "storybook-addon-mock": "^4.3.0",
    "style-loader": "^3.3.4",
    "stylelint": "^15.11.0",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-config-standard-scss": "^11.1.0",
    "terser-webpack-plugin": "5.3.10",
    "typescript": "^5.4.3",
    "uglify-js": "^3.17.4",
    "url-search-params": "^1.1.0",
    "webpack": "^5.91.0",
    "webpack-assets-manifest": "5",
    "webpack-bundle-analyzer": "^4.10.1",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.2",
    "webpack-merge": "^5.10.0",
    "webpack-remove-empty-scripts": "^1.0.4",
    "webpack-sources": "^3.2.3"
  },

**Comment by fturmel** [comment]
Some thoughts:

I'm guessing it could be related to having both v2 and v3 in your code base through transitive dependencies, and their type definitions end up clashing. The v2 types were declared in a global way and taking over the 'date-fns' module namespace, so it's possible that they would overwrite the v3 types.

Additionally, `date-fns-tz` is not v3 ready yet AFAIK, so I would advise holding off a migration to v3 if you rely on this third party package. There are [beta releases on npm](https://www.npmjs.com/package/date-fns-tz?activeTab=versions) though, so that's promising.

Using the "why" and "list" commands in your package manager for further analysis could be useful here. Try to get back to a state where only v2 or v3 are used.

---

An idea to explore: you can [install v3 with an alias](https://stackoverflow.com/questions/56134857/how-to-install-npm-package-under-alias-or-different-name) (ex: 'date-fns-v3') and the types should be correct when you import from that alias in your app. v2 steps over the 'date-fns' namespace, but with an alias you end up shielding v3 from that behavior. Note that it won't resolve the previously mentioned `date-fns-tz` compatibility.

In package.json:
``` 
"date-fns-v3": "npm:date-fns@^3.6.0"
```

Then import from the alias:
```js
import { parseISO } from 'date-fns-v3/parseISO';
```

---

Using a named import from the root works in both v2 and v3 and your bundler should usually be able to tree-shake the unused date-fns functions properly.

```js
import { parseISO } from 'date-fns';
```

Using the default import might be OK as well (did you try?). While the v3 source code only has named exports, there _is_ an `export default` fallback injected during the build phase of the project ([source](https://github.com/date-fns/date-fns/blob/main/scripts/build/modularized.ts)).

```js
import parseISO from 'date-fns/parseISO';
```

However, note that if the root problem is really a clash between v2 and v3 types, you might get rid of the import errors but you'd still be getting v2 type definitions while actually using v3 - which could cause some unexpected behaviors.

Hope that was helpful, good luck!

**Comment by filipkis** [comment]
Thank you this is very helpful. 

Just to add a bit of context. Where slowly transitioning to TS, so now we're resolving these errors, while in fact we've had this setup (with these versions of packages) for a while now and didn't see an issue. 

So I'm wondering, when you say

> Additionally, date-fns-tz is not v3 ready yet AFAIK, so I would advise holding off a migration to v3 if you rely on this third party package

Are you saying there might be breaking issues there? We haven't noticed any so far, but feature where this is used is not very much used anyhow so it might be we're just lucky :) 

> Using the default import might be OK as well (did you try?). 

Yes we tried that and that did work, but I didn't check if it's picking up the correct types. Btw. do you plan to keep that "fallback" on the long run?

**Comment by filipkis** [comment]
I confirmed now it was indeed related to having both versions. 

I managed to resolve it with a modification in `tsconfig.json` by doing something similar to this:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "date-fns": ["node_modules/date-fns"]
    }
  }
}
```

And that forced TS to look for the first instance. And this feels like the cleanest solution as I don't need to use alias + rewrite all the imports and I get the correct versions.

Thanks for the hint on the direction to look for.

**Comment by fturmel** [comment]
Thanks for confirming and sharing your solution! Glad you found a way to make it work.

> Are you saying there might be breaking issues there? We haven't noticed any so far, but feature where this is used is not very much used anyhow so it might be we're just lucky :)

Yes, but it's possible that you were just lucky and the date-fns-tz functions used were OK because they did not rely so much on date-fns itself. The major problem I believe is related to the fact that date-fns v3 stopped exposing some internal/undocumented functions that date-fns-tz was relying upon.
