### ISSUE TITLE
Why the unpacked size of v3.6.0 is 22.2MB?

### ISSUE THREAD

**Issue by liuzhuan** [date-fns/date-fns#3773]
What happened to v3.6.0? The comparison data is as follows:

| version | unpacked size | link |
| --- | --- | --- |
| v3.6.0 | 22.2 MB | https://www.npmjs.com/package/date-fns/v/3.6.0 |
| v3.5.0 | 4.93 MB | https://www.npmjs.com/package/date-fns/v/3.5.0 |

**Comment by kossnocorp** [comment]
That's right. The dual ESM/CommonJS support and now also the CDN versions affect most of the unpacked size.

I understand it might concern you or even affect your application if you use Electron. However, it's a widespread problem that can only be solved by npm/Electron/etc rather than date-fns, so I don't plan to do anything about it until there's a systematic solution.

**Comment by liuzhuan** [comment]
@fturmel @kossnocorp Thanks a lot!
