### ISSUE TITLE
Add days adds 23 hours on daylight saving time transition day

### ISSUE THREAD

**Issue by vincaslt** [date-fns/date-fns#3876]
Here's an example: https://stackblitz.com/edit/date-fns-playground-zprwol?file=index.ts

When adding 1 day on DST day it instead adds 23 hours: `addDays(new Date('2024-03-31T00:00:00.000Z'), 1)` returns `2024-03-31T23:00:00.000Z`

Is that expected? Adding 24 hours to the same date returns `2024-04-01T00:00:00.000Z` which is what I would expect.

**Comment by kossnocorp** [comment]
I have to assume you're in `Europe/Vilnius`, so all the calculations are done in the time zone. If instead of looking at UTC, you look at the local time, it works as expected:

![CleanShot 2024-09-15 at 11 20 49@2x](https://github.com/user-attachments/assets/d3ad75b1-a5ed-4c2c-9b49-0273061150fd)

If it were not considering DST and introducing the shift, the `addDays` wouldn't work consistently as it does right now:

![CleanShot 2024-09-15 at 11 25 27@2x](https://github.com/user-attachments/assets/54c58043-450e-430e-a197-c39fe78ded8a)

Now, I also have to assume you don't care about the local time zone, so in this case, I would recommend you use [`UTCDate`](https://github.com/date-fns/utc) or [`TZDate`](https://github.com/date-fns/tz) (`TZDate` works only with v4, which is in beta rn `date-fns@4.0.0-beta.1`):

![CleanShot 2024-09-15 at 11 31 24@2x](https://github.com/user-attachments/assets/07fcc47e-60b5-40ea-b701-e80f5330b55c)
