### ISSUE TITLE
Type issue in 4.1 using with Zod

### ISSUE THREAD

**Issue by tacomanator** [date-fns/date-fns#3905]
Following code works but gives a type type error as of 4.1:

```ts
import { startOfMinute } from "date-fns/startOfMinute";
import { z } from "zod";

z.date().transform(startOfMinute);
```

Error:
```
Argument of type '<DateType extends Date, ResultDate extends Date = DateType>(date: DateArg<DateType>, options?: StartOfMinuteOptions<ResultDate> | undefined) => ResultDate' is not assignable to parameter of type '(arg: Date, ctx: RefinementCtx) => Date | Promise<Date>'.
  Types of parameters 'options' and 'ctx' are incompatible.
    Type 'RefinementCtx' has no properties in common with type 'StartOfMinuteOptions<Date>'
```

It's pretty easy to reproduce, but here is a reproducible example for convenience:

https://github.com/tacomanator/date-fns-4-zod

after doing `pnpm install`, try and build to reproduce error. Downgrade to 3.6 and the build will succeed.

Note that with either version, the actual output works as expected (run app to see).

**Comment by RonakSurana-2001** [comment]
Can you guide me to the directory where you found the issue

**Comment by gtmetric** [comment]
As the error suggests, the types are incompatible.

Here is how I would do it:
```ts
import { z } from "zod";
import {
    startOfMinute,
    type StartOfMinuteOptions,
} from "date-fns/startOfMinute";

const schema = z.date().transform((date, ctx) => {
    // define the options as needed
    const options: StartOfMinuteOptions<Date> = {};
    return startOfMinute(date, options);
});

// or simply
const schema = z.date().transform((date) => startOfMinute(date));
```

It works on v3.6 and not on v4.1 because of the reason below.

In v3.6, `startOfMinute` only takes one argument: `date`.
In v4.1, `startOfMinute` takes two arguments: `date` and an optional `options`.

```ts
// Doing this
z.date().transform(startOfMinute);
// is the same as this
z.date().transform((date, ctx) => startOfMinute(date, ctx));
//                        ^ RefinementContext         ^ expects StartOfMinuteOptions<Date>
```
Since the second argument of the callback in `transfrom()` is a `RefinementContext` from `zod`, it's incompatible with the second argument of `startOfMinute`, which expects a `StartOfMinuteOptions<Date>` object.

There is no issue in v3.6 because `startOfMinute` didn't have a second argument, so it ignored the `ctx`.
