### ISSUE TITLE
Global options for format and more

### ISSUE THREAD

**Issue by whitneyland** [date-fns/date-fns#456]
Would be great to be able to set global options, so defaults could be changed.  For example, the default for formatting could be:
DateFns.options = {
    "format" : {
        "formatStr" : "MM/DD/YYYY"
    }
}
Then you could call DateFns.format(date) with only one param and get a standard format.

Could apply to other defaults as well.

**Comment by wmertens** [comment]
Hmmm, if  you have a larger application you could end up with conflicting settings. Much safer to just use a wrapper function that applies the defaults.

**Comment by leshakoss** [comment]
@whitneyland date-fns is supposed to be based on pure functions so I have to drop "will not implement" on this issue. This is how you do it if you really wish to use global variables:
v1: https://github.com/date-fns/date-fns/blob/v1/docs/i18n.md#usage
v2: https://github.com/date-fns/date-fns/blob/master/docs/i18n.md#usage

**Comment by whitneyland** [comment]
Ok cool, thanks for listening and the suggestions.

**Comment by twoco** [comment]
I would considering it again to have a global config for date-fns. I found this issue here and I have a similar request and ask here before creating a new issue. It's about i18n. In my opinion there should be a global config for date-fns to set the language for all methods. Instead of wrapping it. It's not consistent. Anyway... my suggestion:

```js
import { config } from 'date-fns';
import { de } from 'date-fns/locale';

config({
  locale: de
])
```

This sets the current language. This can be changed at any time.
