### ISSUE TITLE
Optimise compare_asc

### ISSUE THREAD

**Issue by pke** [date-fns/date-fns#461]
Couldn't that function be much simpler, since its using native `Date` object?

```es6
function compareAsc (left, right) {
  return parse(left) - parse(right)  
}
```

**Comment by leshakoss** [comment]
@pke your solution certainly works correctly with `Array::sort` (and I personally prefer it to our `compareAsc`) but `compareAsc` and `compareDesc` were one of the first functions added to `date-fns`, back in `v0.14.10`, and since then these functions could only return `1`, `0` or `-1`. I don't want to change the functions because it may break some old code, if someone uses something like `if (compareAsc(date1, date2) === -1) {...}`

**Comment by pke** [comment]
Understood! Legacy code. Always a pain. There should have been a lessThan and greaterThan olderThan newerThan function alongside isEqual and we wouldn't have to support this kind of missussage of a compare function.
