### ISSUE TITLE
Parsing two digit years should be possible to configure

### ISSUE THREAD

**Issue by ldrick** [date-fns/date-fns#514]
I tried to replace moment with date-fns, but stumbled across two digit years.

Please see reference on moment: [moment#parse](https://momentjs.com/docs/#/parsing/).
You could specify `moment.parseTwoDigitYear` that enabled me to make it work like Java [java.text.SimpleDateFormat#parse](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html)

Currently it seems baseDate is used, that resolves like this:
```javascript
parse("14-03-14", "DD-MM-YY", new Date(0)) === new Date(1914, 3-1, 14, 0, 0, 0, 0)
```
But `new Date(2014, 3-1, 14, 0, 0, 0, 0)` would be, what my users expect of me.

**Comment by raine** [comment]
Also stumbled on a problem with two digit years.

I have a function that is supposed to parse dates in either two or four digit format, `24.1.2017` or `24.1.17`.

In my attempt to do so I parse the date in each format, starting with longest one, and pick the first valid date.

```js
const formats = ['D.M.YYYY', 'D.M.YY']
const parsed = formats.map(fmt => parse(str, fmt, now))
const date = parsed.find(isValid) || new Date(NaN)
```

However, `parse('24.1.17', 'D.M.YYYY', new Date())` returns the date `0017-01-24T21:00:00.000Z`, which is obviously not what I want.

Any ideas how to work around this?

**Comment by ssimo3lsuhsc** [comment]
The parsing of two-digit years is something that is sorely needed. @leshakoss, in case you did not know, Moment.js parses two-digit years greater than 68 as 1969-1999 and years 68 and under as 2000-2068. So, for example, 68 would be 2068, while 69 would be 1969. I believe that it would have been nice to know this cutoff when you first wrote the 2.0.0-alpha `parse()` function so that you could adopt it.

**Comment by leshakoss** [comment]
@ssimo3lsuhsc if it still works as I intended, token `'YY'` in `parse` sets the year, taking the first two digits from [baseDate](https://github.com/date-fns/date-fns/blob/master/src/parse/index.js#L109) (3rd argument).

Here: https://github.com/date-fns/date-fns/blob/master/src/parse/_lib/units/index.js#L29-L35 is the code responsible for it.

So if `baseDate` is `'2000-01-01'`, the year will be parsed as 20YY; and if `baseDate` is `'1900-01-01'`, the year will be parsed as 19YY.

There was another way I thought of, where `baseDate` sets interval of ±50 years. E.g., if `baseDate` is `'2010-01-01'`, then it sets years 1960–2060. Please let me know your thoughts about it. If you think that this is more logical behaviour, we could fix it

**Comment by leshakoss** [comment]
@raine well, 17 A.D. is still a valid year, isn't it? I would suggest using regexps to check the validity of date formats. Like this:

```js
const formats = [
  {format: 'D.M.YYYY', pattern: `\d{1,2}\.\d{1,2}\.\d{4}`},
  {format: 'D.M.YY', pattern: `\d{1,2}\.\d{1,2}\.\n{4}`}
]
const fmt = formats.find(({pattern}) => pattern.match(str)).format
const parsed = parse(str, fmt, now)
```

`parse` is a wrong tool for checking a validity of a date anyway

**Comment by SimonLuckenuik** [comment]
Is the final decision to leave it as is? 

I do like the way you implemented the 2 digits parsing using the base date, but I should have a way to opt-out.

Personally, I think that if I use the YYYY in the format, only the 4 digits year should be valid, if I use YY in the format, only the 2 digits should be valid. Maybe consider adding optional parameters for example “{YY}YY” would mean that I want 4 digits, but that I would allow the 2 digits logic to be acceptable. 

The goal of parsing is to convert user or system inputs to a date. If I enter the following format: MM-DD-YYYY and convert the user input while he is typing, out of nowhere, the value will be considered valid even if the 4 digits of the years are incomplete. 

If we want people to migrate from other libraries to this one, I think we should listen to this kind of comment and understand what developers are doing with those libraries (and try to do with your library).  In our case, the goal is to have that pattern configurable by user for form display/filling, and I don't think any user will guess that YYYY also supports 2 digits. I initially came here to raise a bug, because the current default behavior is not obvious or expected in my view.

**Comment by megastef** [comment]
Hi, we got a similar problem. But we use new Date() as base date. Insteado fe getting 2018 as year, we get 2020. 

```
df.parse(‘18/03/30 19:37:59,819’, ‘YY/DD/MM HH:mm:ss,SS’, new Date())
2020-06-03T17:37:59.810Z
```

**Comment by nhducseuit** [comment]
I was trying to switch to `date`fns` from `moment` but then realize that `date-fns` cannot parse date in format `dd/MM/yy`
So `date-fns` is still like a vision to me.

**Comment by kossnocorp** [comment]
@nhducseuit hey, that's not nice to call someone's work a vision if it doesn't do what you want precisely how you want it.

As @leshakoss noted, it works like that:

```js
parse('19-01-01', 'yy-MM-dd', Date.now())
//=> 2019-01-01T07:30:34.329Z
```

I don't see anything actionable in this issue, so I'm closing it.
