### ISSUE TITLE
es6 npm version

### ISSUE THREAD

**Issue by cmcguire79** [date-fns/date-fns#516]
Hi

Is it possible to get an es6 npm version so as to work with webpack3 module concatination?

Thanks
Cathal

**Comment by thisconnect** [comment]
There is a module field in package.json, see `"module": "esm/index.js"` https://github.com/date-fns/date-fns/blob/master/package.json#L13

**Comment by kossnocorp** [comment]
@cmcguire79 which version you use? Since `date-fns@2.0.0-alpha.1`, date-fns has ECMAScript modules support; you can see the docs: https://github.com/date-fns/date-fns/blob/master/docs/esm.md. The final v2 release is coming.

If you have a webpack configuration-specific problem, please re-open the issue with your config attached.
