### ISSUE TITLE
V2 missing folders after NPM install (distance_in_words_to_now)

### ISSUE THREAD

**Issue by mesqueeb** [date-fns/date-fns#518]
Hello,

I did `npm install date-fns --save` but there was no folder `distance_in_words_to_now` saved inside the date-fns folder in node_modules.

**Comment by mesqueeb** [comment]
It seems that in V2 it uses a function called `formatDistance` instead. are there any docs for this?

**Comment by kossnocorp** [comment]
@mesqueeb You have installed v2.0.0-alpha.1 because I forgot to mark it as a prerelease. Please try again, it must be installing v1 (v1.21.1) now. 

If you want to play with alpha.1, you can see [the change log](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#change-log) and [JSDoc notations](https://github.com/date-fns/date-fns/blob/master/src/formatDistance/index.js#L13)

**Comment by mesqueeb** [comment]
@kossnocorp Thanks!
I found that the formatRelative docs should be here:
https://date-fns.org/docs/formatRelative
 But it only loads a blank page when I visit that link. : S

**Comment by kossnocorp** [comment]
@mesqueeb yeah, website update isn't deployed yet 😇

**Comment by mesqueeb** [comment]
Oh! That's a shame!
I read the formatRelative source data. Is it possible to cut off the "time" section from this?
> * | Previous 6 days           | last Sunday at 04:30 a.m. |
> * | Last day                  | yesterday at 04:30 a.m.   |

Just have it display as "yesterday" or "last Sunday" ?

**Comment by kossnocorp** [comment]
@mesqueeb it's a good idea, can you open a dedicated issue for this feature request or even better send a PR? Thanks!

**Comment by mesqueeb** [comment]
`result.substring(0, result.indexOf(' at'));`
