### ISSUE TITLE
Is time-fns treeshaking dependant on Uglify?

### ISSUE THREAD

**Issue by mesqueeb** [date-fns/date-fns#521]
I wonder if time-fns alpha 2 treeshaking is dependant on Uglify?
If so I was just worried about this open issue about it:
https://github.com/webpack/webpack/issues/2867

How can I know if the treeshaking is working properly?

**Comment by brigand** [comment]
Late response, so this is mostly for people that find this issue in the future.

That issue is for if you import something, and then don't use it. It doesn't apply to things you didn't declare in the imports. Any decent linter would complain about that import, and then you'd remove it. Problem solved.

I don't think tree shaking is dependent on a minifier, but you'll be using one in production either way. It does depend on webpack 2 or rollup.

You need to configure babel or typescript to output ES6 modules for tree shaking to work. By default, presets like babel-preset-es2015 and babel-preset-env will produce common.js modules.

**Comment by kossnocorp** [comment]
Tree-shaking wasn't working for date-fns for 100% due to https://github.com/webpack/webpack/issues/2867. The upcoming webpack 4 has `side-effects` flag that will allow us efficiently remove unused code. See issue: https://github.com/date-fns/date-fns/issues/565 and a working demo: https://github.com/date-fns/date-fns/pull/566.
