### ISSUE TITLE
Underscore prevents use in NativeScript on Android

### ISSUE THREAD

**Issue by sittingbool** [date-fns/date-fns#542]
Less an issue just to let you and others who come to the same struggle know. I was programming an NativeScript-App on Angular 4 and was using this module. Everything was fine as long as you run in dev mode on emulator. But after making a release build on Android the app always crashed directly after start. I was going mad about this because I couldn't find a solution. I found the reason after 3 weeks and a very angry customer waiting for results: Android can't handle the underscore used in the locale/_lib folder. Underscores in the directory names seem to be fine as long as they aren't the first char. After manually changing the dir name as well as the require statements my app worked fine. Maybe you will think about changing this. In the meantime I have to use moment.js plus my own code to accomplish the same thing.

**Comment by kossnocorp** [comment]
Ouch, this is bummer. I'm sorry to hear that!

It's possible to change this, but it's legit to have a name starting with `_` in *nix systems, so I assume there is a bug somewhere in the stack you're using. In my opinion it's better to fix the problem there rather than introduce workarounds into libraries.

I recommend to open an issue in NativeScript compiler and/or build system you have.

I'm closing the issue for the time being.

**Comment by sittingbool** [comment]
The Problem is Android rather than NativeScript. Android does not allow underscores in dir names. ReactNative-developers would have the same issue.

**Comment by vincentpalita** [comment]
@sittingbool : did you manage to fix your issue because I am facing today the same problem and never had it before with using date-fns for months.
Thank you.
