### ISSUE TITLE
Parameter ordering is backwards

### ISSUE THREAD

**Issue by chasm** [date-fns/date-fns#545]
Proper parameter ordering and currying is essential to composability.

Here is an example of a typical date-fns function from the v2 docs:

```js
format(date, format, [options])
```

This is backwards. The `format` and the `options` will almost certainly be set infrequently. With this ordering, I have to pass them _every time_.

The proper FP ordering for the arguments puts the date last and curries the function:

```js
format(format, options, date)
```

That allows me to do this:

```js
const myFormat = format('DD/MM/YYY', {})
```

Which returns a function that takes only a date and formats it according to the format and options I supplied. I can then use that function all over my code without having to pass the format and the options over and over again. I can also use that to compose new functions as it takes a single parameter.

An even better choice would be to combine the format and the options into a single parameter. This could be polymorphic, with a String interpreted as a format string and an Object interpreted as an options object, perhaps with a `format` key. Or just take an options object and put the format string in it.

The proper parameter ordering is observed in libraries such as Ramda and Sanctuary (or even Lodash/FP), and these would be much better examples upon which to base v2 of date-fns than the old, poorly-considered underscore or lodash. Otherwise, someone will no doubt fork date-fns to fix the problem. JavaScript hell, anyone?

Please consider making this change _before_ you release v2 with other breaking changes.

And it's not just the `format` function.

**Comment by leshakoss** [comment]
@chasm we've decided to resolve this issue by [reversing the order of arguments specifically in FP-functions](https://date-fns.org/v2.0.0-alpha.1/docs/FP-Guide#usage). Also, we have carefully arranged arguments in the way to make sense in both normal and reversed orders.

For FP-functions, the reversed argument order results in more situation specific arguments to be passed to functions last.

Example:
```js
import {formatWithOptions} from 'date-fns/esm/fp'
import {es} from 'date-fns/esm/locale'

//           <- more project specific args      more situation specific args -> 
formatWithOptions({locale: es})('YYYY-MM-DD[T]HH:mm:ssZ')(new Date())
```

That way, you can pass arguments once and reuse it many times:
```js
const format = formatWithOptions({locale: es})
// ...
const formatISO = format('YYYY-MM-DD[T]HH:mm:ssZ')
const formatISOShort = format('YYY-MM-DD')
// ...
[new Date(), new Date(2018, 0, 1)].map(formatISO)
```

On the other hand, the normal order of arguments for non-FP functions uses the following schema:
```js
import {setHours, format} from 'date-fns'
import {es} from 'date-fns/esm/locale'

const formatResult = format(
  // A subject to apply the action to (i.e. format _this date_)
  new Date(),
  // Additional info for this action (i.e. specific pattern to format the date)
  'YYYY-MM-DD[T]HH:mm:ssZ',
  // All optional arguments in a single object
  {locale: es}
)

const result = setHours(
  // A subject to apply the action to (i.e. set hours to _this date_)
  new Date(),
  // Additional info for this action (i.e. number of hours to set)
  5,
  // All optional arguments in a single object
  { /* ... */ }
)
```

It mirrors the order of arguments in JavaScript standard library for consistency:
```js
const result = new Date().setHours(5)
```

and also puts all optional arguments in a single object passed as the last argument. That way we don't have a need to check the type of arguments like you said:

> This could be polymorphic, with a String interpreted as a format string and an Object interpreted as an options object, perhaps with a format key.

Also, this strictly designates which arguments are required and which are not. Following your suggestion and putting format string in the options object is confusing since it is not an optional argument and must be supplied for the function to work.

**Comment by chasm** [comment]
I'm glad to see that the proper ordering is available. I think it's a mistake to view that as the "reverse" order and to assign it to a lesser status requiring the "FP" module, but that sounds like the lodash method and I'm getting the feeling that there are a lot of lodash fans here. That said, second-class citizen is better than nothing. I'll take it!

Good point on the polymorphic way, though you could just set ISO as the default. But that's probably six of one, half dozen of the other.

Thanks for your prompt and detailed reply. I'll investigate the FP variant. I did try that in the docs (selecting it from the dropdown at top left), but it did not seem to affect the ordering shown. I'll recheck.

**Comment by Phylodome** [comment]
As a data point, regarding the downstream consequences of this, a full-scale reversal of arg order is extremely confusing given the lack of separate documentation for the FP library.

I thought I was going insane trying to debug behavior in the `isBefore`/`isAfter` functions, but it just turns out that the whole set of args is reversed and only documented in one line of the FP guide...

At the very least, perhaps add a reminder on functions whose sole purpose is order-dependent comparison...
