### ISSUE TITLE
Set a timezone

### ISSUE THREAD

**Issue by ahmedelgabri** [date-fns/date-fns#556]
What is the best way to set a timezone on the date object?

```js
const TODAY = new Date();

const TZ = 'America/New_York'
// set the date in TODAY to America/New_York timezone

// or

const TZ_OFFSET = -240
// set the date in TODAY to America/New_York using the offset
```

**Comment by kossnocorp** [comment]
At the _moment_, the best way is to manually calculate the offset using `addMinutes` or `subMinutes`. To do that you need to know the local and desired offset values. date-fns always returns a date in the local TZ, so that you can get local TZ calling `getTimezoneOffset()`:

<img width="298" alt="screen shot 2017-09-12 at 18 05 09" src="https://user-images.githubusercontent.com/52201/30322816-f40d79f6-97e4-11e7-84c6-b54063949bdf.png">

Note that in JavaScript, the offset is positive if the local timezone is behind UTC and negative if it is ahead. In your example, it's vice versa.

This way you'll able to format and render the date in a given TZ It actually won't change TZ value in the date object, so `toISOString` will return time in the selected TZ, but the TZ value will be local.

I hope it makes sense. In the future, I want to add TZ functionality but it will take time.

**Comment by ahmedelgabri** [comment]
Thanks, that's what I did already. But I just wanted to see if there were a better way. For now this is fine, but it will be really great if the library has some TZ support built in.

**Comment by markstos** [comment]
Hardcoding time-zone offsets is a bad practice. They often break when Daylight Saving Time changes. That's why proper time zone support is helpful-- you can get the correct answer all year round!

**Comment by heldr** [comment]
Till is not implemented:

```ts
function formatTimezone(date: Date) {
    const offset = date.getTimezoneOffset();

    return Math.sign(offset) !== -1 ? addMinutes(date, offset) : subMinutes(date, offset);
}
```

**Comment by marnusw** [comment]
There is a proposal for this in #707, but it is on hold until v2 of `date-fns` is out for which there isn't a due date yet.

**Comment by motin** [comment]
Related: https://www.npmjs.com/package/date-fns-timezone

**Comment by maciej-gurban** [comment]
@marnusw Would you consider creating a v1 version? The v2 is still in alpha so it's likely to take awhile before it reaches maturity

**Comment by roboli** [comment]
@heldr handy function worked for me but I had to do a minor change because if I `formatTimezone(parse('1989-07-01'));` it would returned me date as `1989-07-01T12:00:00.000Z`. I'm in Central America so it was adding another 6 hours to UTC:

```
> var myDate = new Date(1989, 6, 1);
undefined
> myDate;
1989-07-01T06:00:00.000Z
> var utcDate = formatTimezone(myDate);
undefined
> utcDate;
1989-07-01T12:00:00.000Z
```

Switching operations worked for me

```
return Math.sign(offset) !== -1 ? subMinutes(date, Math.abs(offset)) : addMinutes(date, offset);
```

```
> var myDate = new Date(1989, 6, 1);
undefined
> myDate;
1989-07-01T06:00:00.000Z
> var utcDate = formatTimezone(myDate);
undefined
> utcDate;
1989-07-01T00:00:00.000Z
```

Or maybe I'm missing something? Anyway... Thanks.
