### ISSUE TITLE
failed to fetch version list

### ISSUE THREAD

**Issue by yuu2lee4** [date-fns/date-fns#581]
docs failed to fetch version list

**Comment by kossnocorp** [comment]
As I see it's temporal problem caused by the Chinese firewall. If the problem persists I would glad to get some feedback how we can improve the situation for Chinese users. FIY we use Firebase.

**Comment by yuu2lee4** [comment]
yeah,it is really a Chinese firewall problem.I want cry.

**Comment by kossnocorp** [comment]
@yuu2lee4 if the site isn't available, you still can access the docs via the source code. See an example: https://github.com/date-fns/date-fns/blob/master/src/addDays/index.js. Since the docs on the site are generated from those JSDoc annotations it's basically the same docs so you won't miss anything.

**Comment by yuu2lee4** [comment]
ok,it can be a temp way.

**Comment by yuu2lee4** [comment]
now,I can open https://firebase.google.com, but still cant fetch version list.
