### ISSUE TITLE
Feature Request: Business Days functionality

### ISSUE THREAD

**Issue by serle** [date-fns/date-fns#584]
Is there any plan to support business day add/subtract calculate from a start and end date. This would need to exclude non-workdays e.g. public holidays and weekdays array.

**Comment by kossnocorp** [comment]
@serle it sounds like a great idea, but I can't promise that we'll work on that in the near future. If you want to help with that, I'll be glad to help you with the guidance.

**Comment by serle** [comment]
@kossnocorp I'm a bit bogged down at the moment, but I have implemented an algorithm on top of the moment.js library, which I'm happy to contribute. I found the standard approach of looping through each day to do a business day test is way too slow for extended durations. i.e. 

1) calculate the number of business days between date1 and date2.
2) add.subtract N business days to dateY

so it required a bit of a specialized approach.

**Comment by rfoel** [comment]
Help still needed?

**Comment by klompenrunner** [comment]
Just like me you might have ended here in search of the additional functionality.

`dateFns.differenceInDays(date1, date2) - dateFns.differenceInCalendarWeeks(date1, date2) * 2`

is meeting my needs for now.

It doesn't exclude holidays days; but excluding those will be such a localization nightmare. Business apps would typically need to follow the businesses holidays anyway.

**Comment by dkozickis** [comment]
This has landed with `date-fns@2.x`. Closing.

**Comment by younes-io** [comment]
Is there a function that sets up the banking holidays ? 
I would expect something like `addBusinessHolidaysToCalendar(holidaysArray)`

**Comment by BenStirrup** [comment]
A feature taking into account holidays would be great !

**Comment by thedamon** [comment]
> This has landed with date-fns@2.x. Closing.

Google brought me here lol.. a name of the new function would be handy. In case anyone else is wondering:

`addBusinessDays`, `subBusinessDays`, `differenceInBusinessDays`

It appears to only use M-F for determining whether something is a business day though so the name "business day" is perhaps misleading.

**Comment by tonmoydebnath100** [comment]
//Here 'form' is a date type variable and 'Days' is numerical variable. 
//subtract only BusinessDays, you can choose any days of a week using isMonday(), isSunday() and etc.
function SubtractBussinessdays(from,Days){
        let i=0,newDate=from;
        Days++;
        while(i<=Days){
          if(isFriday(newDate)){
            Days++;
          }
          newDate=subDays(newDate,1);
          i++;
        }
        return newDate; //it will return the expected date
      }
//add only BusinessDays, you can choose any days of a week using isMonday(), isSunday() and etc.
      function additionBusinessdays(from,Days){
        let i=0,newDate=from;
        while(i!==Days){
          if(isFriday(newDate)){
            Days++;
          }
          newDate=addDays(newDate,1);
          i++;
        }
        return newDate; //it will return the expected date
      }

**Comment by KristofDeTroch** [comment]
I will be building an application in the coming weeks that will very heavily rely on a similar feature with support for custom calendars. Extending this would make a lot of sense for me, but I see that the last release was already a few months ago, so I'm wondering whether it makes sense to work on this in the library and create a pr or the maintainers are not active enough to know that this could be merged in a couple of weeks?

**Comment by tevinch** [comment]
For the custom-calendar part of this request, I checked date-fns 4.4.0: `addBusinessDays` still counts Monday–Friday; the custom weekdays/exceptions proposal in #3480 has not been merged.

I put a [free MIT date-only calendar and runnable checks here](https://github.com/tevinch/data-shape-kit/tree/main/examples/work-calendar). It supports custom working weekdays, supplied holiday dates, positive/negative offsets and interval counts:

```ts
import { createWorkCalendar } from './work-calendar.js';

const calendar = createWorkCalendar({ holidays: ['2026-01-02'] });
calendar.addWorkdays('2026-01-01', 1); // '2026-01-05'
calendar.addWorkdays('2026-01-05', -1); // '2026-01-01'
calendar.countWorkdays('2026-01-01', '2026-01-08'); // 4
```

The holiday is an example application-supplied closure. Counts use `[start, end)` and reverse sign for reversed intervals; nonzero offsets exclude the starting date, while zero preserves it. Holidays already on non-working weekdays are not counted twice.

For long intervals, it counts whole weeks and searches sorted holiday dates, then uses bounded binary search for offsets instead of walking each intervening day. The guide shows date-fns integration with an explicit time zone. Input/output is a calendar-date string, so preserving a clock time or converting the result to an instant is a separate step. This is an independent option, not an upstream change or a regional holiday database.
