### ISSUE TITLE
Add isFirstWeekInMonth helper

### ISSUE THREAD

**Issue by KuznetsovIlya** [date-fns/date-fns#601]
We are using 'date-fns' lib in our app and found helper like this to be useful for use-cases like when you want to add specific styles to first week-item in month in week-scale diagram . #600

**Comment by leshakoss** [comment]
Wouldn't function like `getWeekOfMonth` be usable in more use-cases?

While I agree that your use-case is valid, I don't like the idea of having `isFirstXOfY` and `isLastXOfY` for any combination of two units of time and would prefer `getXOfY` to be used instead as it is more flexible (so `getXOfY(date) === 1` instead of `isFirst...`; and `getXOfY(date) === getXInY(date)` instead of `isLast...`)

Please tell me your thoughts about it

**Comment by KuznetsovIlya** [comment]
Well, yes, it's make sense) thanks for reply, I'll try it
