### ISSUE TITLE
startOfToday not returning the correct date

### ISSUE THREAD

**Issue by arunprakashpj** [date-fns/date-fns#654]
startOfToday() method does not return correct date time. when I ran the script through nodejs it returns yesterdays date with 18.30 as time instead 00.00.00

**Comment by leshakoss** [comment]
@arunprakashpj could you please elaborate? What does it return? Which time zone are you in?

**Comment by arunprakashpj** [comment]
^^^

**Comment by arunprakashpj** [comment]
when I ran the script through nodejs it returns yesterdays date with 18.30 as time instead 00.00.00(set ur time zone different and check)

**Comment by yrshaikh** [comment]
@arunprakashpj still have this problem? Can you also tell me the following, to make it more obvious -
1. What date and time you ran?
2. Expected time 
3. And what did you get?

**Comment by arunprakashpj** [comment]
Actually, the problem didn't get solved. I preferred an alternate library.

**Comment by leshakoss** [comment]
It was probably a misleading behaviour by REPL of node.js. By default it prints out dates in timezone +00:00, as if using the `toISOString` method on a date. Using `toString` method would print out a date in the local timezone. Looks like this:

<img width="307" alt="screen shot 2018-05-13 at 22 57 48" src="https://user-images.githubusercontent.com/566319/39971754-20e16394-5701-11e8-8074-f420e3f70d7f.png">

Anyway, closing this issue because it is no longer relevant
