### ISSUE TITLE
Distinguish between 2018-01-01 and 2018-01

### ISSUE THREAD

**Issue by tremby** [date-fns/date-fns#679]
A valid ISO date format is YYYY-MM, such as 2018-01. If I parse 2018-01 into date-fns and then run getDate on it, I get 1. I'd expect null.

Is this a bug, or is assuming the first of the month expected behaviour?

I'd like to be able to distinguish between dates where the day was given and dates which are only accurate to the month. Is that possible with date-fns?

**Comment by leshakoss** [comment]
> Is this a bug, or is assuming the first of the month expected behaviour?

It is expected behaviour. Same for all partial ISO 8601 dates, e.g. if only the year is specified, date-fns will assume the start of the year.

> Is that possible with date-fns?

It is not possible with date-fns and unfortunately will never be. date-fns uses plain JavaScript's [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object, which is basically a wrapper over a single value (timestamp) and does not have separate properties year, month, day, etc.

**Comment by leshakoss** [comment]
> Is this a bug, or is assuming the first of the month expected behaviour?

It is expected behaviour. Same for all partial ISO 8601 dates, e.g. if only the year is specified, date-fns will assume the start of the year.

> Is that possible with date-fns?

It is not possible with date-fns and unfortunately will never be. date-fns uses plain JavaScript's [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object, which is basically a wrapper over a single value (timestamp) and does not have separate properties year, month, day, etc.
