### ISSUE TITLE
When will v2.0 be available in NPM so I can access esm features?

### ISSUE THREAD

**Issue by venicia** [date-fns/date-fns#698]
If it is there, how do I install it?  The 'yarn add date-fns' is pointing to v1.

**Comment by scttcper** [comment]
`yarn add date-fns@next` gets the beta you can see published versions https://preview.npmjs.com/package/date-fns

**Comment by kossnocorp** [comment]
Sorry, there is no ETA. This is a very hot question, and we ask it ourselves all the time.

I'll explain the situation in detail so I'll be able to reuse this comment every time someone asks us the question.

I'm (the author) was backing the development of date-fns from my funds. I did pay salary to @leshakoss (the main contributor) for quite a while. About year ago I left my job, and now I'm bootstrapping my own business. I don't have that much time and resources to push things faster than they're moving right now. Lesha is employed full time and also can't spend more time than he spends.

Another factor is that we don't want to contribute to JavaScript fatigue and make people rewrite they projects every few months. We value stability and consistency and want to release API that will stay the same for years.

So thank you for patience. I'm pretty sure that you'll love v2.

**Comment by duclet** [comment]
But yet, with each alpha release, there is generally a breaking change (so the consistency is gone) and/or new features being added (decreasing stability). While I understand we want finalize things as best as we can, I would also say there should be a limit to how long it takes. Over a year is really pushing it in my view but again, I'm not going to force you to do anything. I would want to adopt date-fns within my company but the unavailability of a stable release without API changes within the next one, makes it not possible. Keep up the good work on the project though because it does have quite a few things I like but until it is "stable", I'm not going to be able to convince many people at my company to use it (myself included).

**Comment by kossnocorp** [comment]
@MiracleBlue thank you so much for the kind words, Nicholas! ❤️ It's important to us hearing such feedback, thank you again! I'm looking forward to seeing you on the list of contributors. 🤗

**Comment by MiracleBlue** [comment]
My pleasure!  Yes, I also hope to be on the contributors list at some point in the near future.

Hope you're all having a great day!

**Comment by SampsonCrowley** [comment]
@kossnocorp can we at least add a release to v1 that exports ES modules? I'm stuck between alpha releases and CJS only

**Comment by SampsonCrowley** [comment]
meaning would a rewrite PR of the build-process in v1 (no actual usage changes) to use v1 as ES Modules be accepted?

**Comment by kossnocorp** [comment]
No, sorry, I will not accept a PR to v1 with any substantial changes. Right now v1 release and docs generation/upload is cumbersome and hacky, so it takes a lot of my time that I rather spend on v2.
