### ISSUE TITLE
BE (Belarusian) language support

### ISSUE THREAD

**Issue by mawi12345** [date-fns/date-fns#703]
We are working an translation for v1.

**Comment by desigens** [comment]
If you need help, contact me.

**Comment by mawi12345** [comment]
@desigens could you pleas check the pull request.

**Comment by desigens** [comment]
The biggest issue in PR is that Belarusian language has more complex than two "one-many" word forms.  So phrase "N секунд(-ы)" can be more human:
- 1,21,31 секунда
- 2,3,4,22 секунды
- 5,6,7 секунд

If you don't mind, I can create new PR.

**Comment by mawi12345** [comment]
I would be great if you could create a PR. I do not speak Belarusian and the translator we paid for did not manage to communicate the complexity of the language.

**Comment by kossnocorp** [comment]
@alyrik that would be great if you could help to port the PR. Releasing v1 and then porting the code back to v2 causes a lot of headaches, so that's why it still open. Eventually, I plan to deal with v1 PRs, but I can't promise that there'll be another v1 version.

Here is the guide that will help you update the locale: https://date-fns.org/v2.0.0-alpha.18/docs/I18n-Contribution-Guide

I understand that's frustrating but final v2 is the priority, so I don't want to spread our efforts too thin.

**Comment by kossnocorp** [comment]
Closed for v1 by https://github.com/date-fns/date-fns/pull/716. I'm going to publish a new v1 soon. Whoever still wants to port it to v2 — please do.

**Comment by kossnocorp** [comment]
The locale was released with `v1.30.1`. See: https://blog.date-fns.org/post/v130-is-out-m35nqh4m13r7
