### ISSUE TITLE
Is this library still actively moving forward?

### ISSUE THREAD

**Issue by benjamincharity** [date-fns/date-fns#729]
I've used this on several projects and really like it. But I've noticed that 2.0.0 has been in alpha for almost a year now.. are things still moving forward here?

**Comment by mesqueeb** [comment]
@benjamincharity 
If you look at the commits: https://github.com/date-fns/date-fns/commits/master
You can see that the main developer works on it a few days each month. From what you can derive of the history you can see it's mostly merging pull requests from the community.

Therefor I can give as advice to dig into the source code, find some places you can help out and make a pull request! I'm also waiting for the BETA version myself. Should be coming soon! ♡

Personally I still needed some extra `locale` support, and there has recently been a huge overhaul of these, so now a lot of languages are not supported anymore because they need updating. That might be a good place to start!

**Comment by fabienjuif** [comment]
@mesqueeb what could be cool is to add the `good first issue` for new comers!
