### ISSUE TITLE
Invalid Date on firefox , parse routine returns invalid date.

### ISSUE THREAD

**Issue by richie50** [date-fns/date-fns#742]
On firefox:
Name 	Firefox
Version 	60.0
Build ID 	20180503143129

The parse routine returns invalid date when the specified argument to the routine is `"<day>-<month>-<year>"`  example "07-May-2018". This does not happen on chrome.

**Comment by leshakoss** [comment]
@richie50 could you please give us the exact line of code which works differently in different brothers?

**Comment by richie50** [comment]
`let formatedDate = isToday(value) ? "Today" : isTomorrow(value) ? "Tomorrow" : format(value, 'dddd MMM D');`
the value is `"01-May-2018"` . @leshakoss you can try any date format in that specified order. Thanks

**Comment by leshakoss** [comment]
@richie50 well, basically, values like `"01-May-2018"` shouldn't have been supported in the first place. It works in Chrome because `parse` falls back to `new Date` if it fails to parse ISO-8601 string. So please don't use strings like that as arguments. In the next version of date-fns we are removing this fallback: #743
