### ISSUE TITLE
parse: Incorrect date on Safari

### ISSUE THREAD

**Issue by ValentinH** [date-fns/date-fns#759]
The following date string isn't parsed correctly on Safari: `2014-03-01Z`. The problem comes from the timezone indicator, is it a bug or is it this date that isn't valid?

See this sandbox(in `src/index.js`): https://codesandbox.io/s/619rj61lrz

**Comment by kossnocorp** [comment]
Hey. The problem is that the date isn't valid [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) string. Previously we used `new Date(str)` as a fallback but because of inconsistent browsers behavior [we did remove it](https://github.com/date-fns/date-fns/pull/744) and starting from `date-fns@2.0.0-alpha.9` it will be returning an invalid date.

**Comment by ValentinH** [comment]
Thanks for the clarification and for this great library! 💪

**Comment by phil-w** [comment]
Just encountered this myself. If you feed fully formatted ISO-8601 dates to Mac OS 10.13/Safari 11 all sorts of bad things result. Truncating the time portion works around that issue.

**Comment by kossnocorp** [comment]
@phil-w please provide example strings that cause Safari to fail and the date-fns version.

**Comment by kossnocorp** [comment]
@phil-w the provided string isn't valid ISO-8601 string so no surprise it fails. In v1 we fallback to browser's `new Date()` while in v2 we don't, to prevent this very issue. I'm not sure how to help you, but keeping dates in the standard format is generally a good idea.
