### ISSUE TITLE
Granularity

### ISSUE THREAD

**Issue by Christilut** [date-fns/date-fns#869]
I couldn't find it in the docs, but is there a granularity option like Moment has?

For example:
```
date.isAfter(Moment(), 'day') 
```

I want my `date` to be after today (regardless of time).

**Comment by jemerald** [comment]
Could compose with `startOfDay`: `isAfter(startOfDay(date1), startOfDay(day2))`

**Comment by dkozickis** [comment]
Closing as workaround was provided. 
@Christilut - please re-open if you have further questions.

**Comment by enzoferey** [comment]
@dkozickis Hi ! Do you think this is a feature we want inside the library ? I have myself implemented it in my projects as it's straightforward to due with all the existing `startOf*UNIT*` functions. I would be glad to send a PR, and if you provide me some indications about how you invision it in the codebase it would be perfect 👍

**Comment by kossnocorp** [comment]
@enzoferey could you please tell first how do you use this function? My concern is that such function adds extra bytes to your build size (this function would bundle 6 other functions) and that people would start using it without an actual need for it.

**Comment by enzoferey** [comment]
Thanks for pointing it out.

I started using this syntax because of a migration from `moment`, which uses this last argument granularity API. I do think having an API like `isBeforeByDay`, `isBeforeByHour`, etc. would make more sense inside the library. It's more explicit, you don't rely on magic strings constants and you would add to the bundle what is required (`isBefore` + `isStartOf*unit*`).

That said, it's only a proposal, I haven't thought in detail about it and I don't know the vision you guys share on how the library should evolve. I do think that people expect this kind of APIs as first class APIs and not as some clever reuse of functions around (proof of that is this issue, myself googling it, and potentially all the people that arrive here but didn't comment).

**Comment by kossnocorp** [comment]
I like the idea of `isBeforeByDay` and similar (but `isBeforeDay`, `isAfterWeek` names will be more fitting), so you or anyone else feel adventurous, feel free to open PR which I'll gladly accept.

**Comment by enzoferey** [comment]
I will open a PR the latest next weekend covering all `isBefore` and `isAfter` variations 👍

**Comment by kossnocorp** [comment]
Nice, thank you a lot!
