### ISSUE TITLE
[ 2.0.0-alpha.16] RU Locale Invalid parse() result

### ISSUE THREAD

**Issue by volodalexey** [date-fns/date-fns#876]
```
const parse = require('date-fns/parse');
const ru = require('date-fns/locale/ru');

parse('13 июня 2018', 'D MMMM YYYY', new Date(), { locale: ru });
```
returns 2018-01-12T22:00:00.000Z

**Comment by kossnocorp** [comment]
Thank you for heads up, I'm going to investigate what's the reason of the issue.

**Comment by kossnocorp** [comment]
Oh, I got confused. This is actually not a bug.

First of all, in v2 we adopted Unicode Technical Standard #35: https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table and tokens have changed. You have to use `d MMMM yyyy` to make it parsed correctly.

The second part of the problem (`22:00`) is caused by console converting your local time (which is actually `00:00`) before printing it.

See 👇

<img width="555" alt="image 2018-09-18 at 9 14 21 pm" src="https://user-images.githubusercontent.com/52201/45708138-570a3300-bb89-11e8-9974-5a28830d76c0.png">
