### ISSUE TITLE
Format bug with december

### ISSUE THREAD

**Issue by juggat** [date-fns/date-fns#954]
Version: `2.0.0-alpha.24`

When using `format`, the last two days of December (meaning `30/12` & `31/12`) returns the next year's date. It works well with `29` and lower.

Example: https://codesandbox.io/s/wojowkpk5w

**Comment by kossnocorp** [comment]
To format the dates you used `YYYY` (local week-numbering year) instead of `yyyy` (calendar year), so it's an expected result. 

```js
console.log(
  format(parse('31 / 12 / 18', 'dd / MM / yy', new Date()), 'YYYY-MM-dd', {
    awareOfUnicodeTokens: true
  })
)
//=> '2019-12-31'

console.log(
  format(parse('31 / 12 / 18', 'dd / MM / yy', new Date()), 'yyyy-MM-dd')
)
//=> '2018-12-31'
```

You can read about the week-numbering year here: https://en.wikipedia.org/wiki/ISO_week_date

This is a popular mistake that we've tried to prevent by requiring `awareOfUnicodeTokens` which you used in your code example. 

I have to ask, what made you put `awareOfUnicodeTokens` and did you read the docs from the exception that I assume you got before you set it?

**Comment by juggat** [comment]
@kossnocorp Thank you for your quick reply.

Seems like I didn't read the doc well enough, I used `awareOfUnicodeTokens` because we used `YYYY` before and it worked fine on the stable version, but it seems like I got mixed up on those new formats.

I didn't notice the link in the exception, but that would have cleared that up, so it's totally my bad 👍 

Thanks again and sorry for the waste of time :)

**Comment by kossnocorp** [comment]
@juggat no worries, you're welcome!
