### ISSUE TITLE
wrong year in parsed date (v2)

### ISSUE THREAD

**Issue by fxck** [date-fns/date-fns#955]
Running `v2.0.0-alpha.24` 

Code:
```
import parse from 'date-fns/esm/parse';

parse('2050-08-01', 'YYYY-MM-dd', new Date());
```

Output:
```
Sun Aug 01 2049 00:00:00 GMT+0200 (Central European Summer Time)
```

Day and month is correct, year is for some reason `-1`.

**Comment by kossnocorp** [comment]
First of all, you use `YYYY` which is an incorrect token for your case. You have to use `yyyy`. Read for about it [in the blog](https://blog.date-fns.org/post/unicode-tokens-in-date-fns-v2-sreatyki91jg) or [in the docs](https://git.io/fxCyr).

Secondly, you either don't use `v2.0.0-alpha.24` or modified your code example because since [`v2.0.0-alpha.22`](https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha22) we don't allow usage of `YYYY` without setting `awareOfUnicodeTokens` option.

**Comment by fxck** [comment]
Right, I was using `next`, which, looking at package-lock, ended up being alpha.16.

Thank you.

**Comment by kossnocorp** [comment]
You're welcome
